### ISSUE TITLE
Add attribution to the Polkadot Wiki

### ISSUE THREAD

**Issue by wpank** [sora-xor/sora2-network#1]
A lot of the readme was copy and pasted from the Polkadot Wiki word for word. The Polkadot wiki is licensed under GPL and requires attribution: https://github.com/w3f/polkadot-wiki/blob/master/LICENSE

**Comment by takemiyamakoto** [comment]
Thanks for pointing this out. This was just a placeholder, so it will be refactored. Deleted content for now.
