### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#10]
- [x] Release checklist 
The current check list contain no specific instructions.
It makes it impossible for a new person to make a release.

- ~[ ] Substrate <-> Relay chain
(https://soramitsu.atlassian.net/wiki/spaces/PLS/pages/2213347329/Substrate+-+Relay-chain+bridge)~

- [x] Onboarding (https://soramitsu.atlassian.net/wiki/spaces/PLS/pages/2249130040/Onboarding)

- [x] Processes (https://soramitsu.atlassian.net/wiki/spaces/PLS/pages/2096562189/Development+process+policies)

- [x] Update Guide to adding token on ETH Bridge to EVM Bridge (https://soramitsu.atlassian.net/wiki/spaces/PLS/pages/3044868099/Guide+for+adding+tokens+to+the+Ethereum+bridge)

- ~[ ] Guide to adding token to Substrate<->Substrate Bridge~

**Comment by bgodlin** [comment]
> Update Guide to adding token on ETH Bridge to EVM Bridge (https://soramitsu.atlassian.net/wiki/spaces/PLS/pages/3044868099/Guide+for+adding+tokens+to+the+Ethereum+bridge)

The updated guide can be found in https://github.com/sora-xor/sora-docs/blob/develop/src/adding-tokens-to-hashi-bridge.md

**Comment by bgodlin** [comment]
> Substrate <-> Relay chain
(https://soramitsu.atlassian.net/wiki/spaces/PLS/pages/2213347329/Substrate+-+Relay-chain+bridge)

> Guide to adding token to Substrate<->Substrate Bridge

Not relevant anymore
