### ISSUE TITLE
ALT: xyk pool quote error

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#1009]
`quote` that uses ALT for order-book & xyk-pool sources with desired amount > order-book liquidity, returns `UnavailableExchangePath` error.
Swap XOR --> Asset
Prices are equal.
xyk-pool reserves are too low.

## Problem root cause
Specifically for `xyk-pool` the problem is related with calculations in `calc_input_for_exact_output` when the denominator becomes negative.

In general, the problem is a case when quote/swap amount exceeds the reserves. We have to check these cases for all sources.

It is possible to fix it for ALT with several sources, because if one liquidity source doesn't have enough liquidity, it doesn't mean that total liquidity of all sources is not enough for a deal.

## Definition of done
- [x] adapt xyk-pool::step_quote for case when reserves are exceeded
- [x] new unit tests for xyk-pool
- [x] adapt tbc::step_quote for case when reserves are exceeded if it's needed
- [x] new unit tests for tbc if they are needed
- [x] check order-book
- [x] check xst
- [x] check ALT with case when total sources liquidity is less then amount
- [x] add irreducible reserve mechanism

**Comment by wer1st** [comment]
It's bug of `xyk-pool` pallet.

Steps to reproduce:
- Create the only source XOR-Asset xyk pool with reserves 1000 XOR = 100 Asset
- swap/quote: XOR --> Asset, with_desired_output 101 (> Asset reserves)
- swap/quote: Asset--> XOR, with_desired_output 1001 (> XOR reserves)

cc @ra9mls @OlgaSamorodnova 

I will fix it for ALT with several sources, but it stays for the only one source `xyk pool`

**Comment by wer1st** [comment]
We have to check similar scenarios for TBC as well.

**Comment by OlgaSamorodnova** [comment]
Checked the situation when I swap the amount which is larger than in XYK and TBC reserves separately.
(for example, 10000 in XYK and 5000 in TBC - I try to swap 12000). In this case, ALT works with both sources.
