### ISSUE TITLE
[Tech]: Pallet for Regulated assets support

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1012]
### Problem statement

We want to support regulated assets

### Definition of Done

- [ ] Implement pallet for regulated assets support
- [ ] Add regulated assets support to assets pallet #1014 

### Requirements

- Transaction can be executed only if all involved users have SBT tokens
- Technical accounts can perform any operations
- Only asset owner can make asset regulated
- First implementation may omit any checks until SBT tokens is not supported

**Comment by Trezeguet1** [comment]
Testing of the task is complete
