### ISSUE TITLE
[Tech]: Expirable Soulbound tokens support

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1013]
### Problem statement

We want to support Soulbound tokens with expiration

### Definition of Done

- [ ] Add SBT tokens support to Regulated assets pallet
- [ ] Deny transfers for SBT tokens
- [ ] Add expiration to SBT tokens

### Requirements

- Expiration should be optional
- This logic should be part of Regulated assets pallet #1012

**Comment by vovac12** [comment]
@Tieumsan should expiration be applied per-user?

**Comment by vovac12** [comment]
New storages:
**(AccountId user_account, AssetId regulated_asset_id) -> (AssetId sbt_token)**
**(AccountId user_account, AssetId sbt_asset) -> Option<(Timestamp expiration)>**

Steps:

1. Check if user have sbt_token
2. Check expiration
3. Perform transfer

Mint expirable sbt flow:

1. Mint SBT with **assets.mint**

2. Set expiration date and regulated asset with 
**regulated_assets.set_expiration(AssetId regulated_asset_id, AssetId sbt_asset_id, Timestamp expiration_date)**

**Comment by Trezeguet1** [comment]
Testing of the task is complete
