### ISSUE TITLE
[Tech]: Permissioned pools support for XYK pool and LiquidityProxy

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1015]
### Problem statement

We want to support permissioned pools

### Definition of Done

- [ ] Add necessary checks to XYK pool pallet for pools with regulated assets
- [ ] Verify if regulated assets support works good with LP logic

**Comment by Trezeguet1** [comment]
Testing of the task https://github.com/sora-xor/sora2-network/issues/1015 is complete
Basic checks have been successfully completed:
mainly creating pools and swap, withdraw and deposit liquidity
it is also impossible to manage liquidity if the SBT expires by time
