### ISSUE TITLE
harvester-worker tasks failures ratio too high

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#102]
sorascan_task_update_balances_ratio_too_high prod sora2 (env: prod, project: sora2, instance: sora2-prod-s1 )
harvester-worker tasks failures ratio too high. Average task failure ratio for task app.tasks.update_balances_in_block is 100 in instance sora2-prod-s1!

**Comment by wer1st** [comment]
@f33r0 is originator of this issue

**Comment by f33r0** [comment]
@wer1st please close this issue
