### ISSUE TITLE
[Tech]: Add support for kXOR to XYK pool

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1023]
### Problem statement

We want to support kXOR in XYK pool pallet

### Definition of Done

- [x] kXOR support in XYK pool
- [x] Ensure liquidity-proxy and other pools works correctly

### Requirements

- Users should be able to deposit and withdraw liquidity with kXOR
- If there's not enough of XOR or kXOR in pool swap fails

**Comment by Tieumsan** [comment]
@vovac12 please elaborate on the technical implementation and sync with @stefashkaa on the additional information needed to prepare for the breaking changes
