### ISSUE TITLE
[Bug]: XSTUSD-XST swaps failing

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#1033]
### Steps to reproduce

Make swap on stage https://test.polkaswap.io/#/swap/XSTUSD/XST with 400 xstusd

### Actual behavior

Slippage not tolerated https://polkadot.js.org/apps/?rpc=wss://ws.framenode-8.s5.stg1.sora2.soramitsu.co.jp#/explorer/query/0xb6873830baf7e3867ad0c724c449b6118b3d20df3096a298a4d2cdc031003a03

### Expected behavior

Swap is Done

### Environment

{"label"=>"Production"}

**Comment by Nolan730** [comment]
Quote of WithDesiredInput, WithDesiredOutput and swap of withdesiredoutput always same but WithDesiredInput gives less so that causes it to fail due to slippage. Executing swap of withdesiredinput with very high slippage(like %50) success and gives waaay less output then others
