### ISSUE TITLE
[Tech]: Replace mock Config implementations with macro

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1053]
### Problem statement

We want to make mocks more readable and reduce code duplication

### Definition of Done

- [ ] Replace `assets::Config` trait impl with macro
- [x] Replace `technical::Config` trait impl with macro
- [x] Replace `pallet_balances::Config` trait impl with macro
- [ ] Replace `frame_system::Config` trait impl with macro
- [ ] Replace `tokens::Config` trait impl with macro
- [ ] Replace `currencies::Config` trait impl with macro
- [ ] Replace `common::Config` trait impl with macro

**Comment by Alexey-N-Chernyshov** [comment]
Macros are [in `common/macros`](https://github.com/sora-xor/sora2-network/blob/master/common/src/mock.rs#L195-L369). [Usage example](https://github.com/sora-xor/sora2-network/blob/master/pallets/kensetsu/src/mock.rs#L229-L237).
