### ISSUE TITLE
[Bug]: Second ETR->Sora bridge transaction takes too long

### ISSUE THREAD

**Issue by adaagava** [sora-xor/sora2-network#106]
### Preconditions

User have enough ETR in Etherium 

### Steps to reproduce

1. Log in to polkaswap web
2. Make the bridge transaction from Etherium to Sora

### Actual behavior

The first transaction lasts about 1 minute
The second lasts more than 30 minutes

### Expected behavior

Both bridge transactions succeed in about 3 minutes

### Environment

{"label"=>"Test"}

### Operating System

macOS Monterey

**Comment by vovac12** [comment]
Probably it was some networking issue on peer node. I'm closing issue as we haven't had this problem again for 2 months
