### ISSUE TITLE
[For UI] Liquidation mechanism improvement

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#1075]
### Problem statement

Currently the liquidation mechanism for any CDP starts when the value of the collateral passes below the collateralisation ratio.

This means that any user who will borrow the maximum amount available will suffer liquidation as soon as the price of the collateral used moves downward.

### Description

To avoid this inconvenience and improve user experience, we want to modify the threshold at which the liquidation starts.

A community member suggested the liquidation starts when the value of the collateral passes below the 100% value borrowed rather than the collateralisation ratio (e.g. 100% instead of 150% if the collateralisation ratio for that vault is 150%).

<br/>

Further analysis on the behavior and requirements is needed before proceeding with the implementation.

### Definition of Done

TBC after business and technical analysis is complete.

### Requirements

TBD

The solution proposed should ensure robustness and security of the protocol and user funds.

**Comment by ra9mls** [comment]
New task will be created for UI
