### ISSUE TITLE
Put orders with KUSD as the quote asset

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#1080]
As a DeFi trader I want to put orders (market, limit) with a stable asset as the quote asset so that I can better anticipate my returns and manage my trading strategy.

<br/>

### **Preconditions**

User holds KUSD tokens.

### **Flow**

1. User puts an order in the Order Book with KUSD as the quote asset.

### **Postconditions**

Order with KUSD \ [ ] is created on the Order Book

**Comment by wer1st** [comment]
The best way is to create new DEX where KUSD will be the base asset, as XSTUSD in dex_id = 1.

**Comment by wer1st** [comment]
Resolved by #1108 
@ra9mls please check
