### ISSUE TITLE
Vault parameter - Liquidity incentive percent

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#1089]
### **Problem Statement**

To encourage XOR-KUSD liquidity, we want to have a percent of the stability fees collected go to LPs that stake their XOR-KUSD liquidity on Demeter farm.

### **Description**

The liquidityIncentivePercent parameter represents the percentage of the stability fee that gets redirected to the Demeter farm on the XOR-KUSD pool.

### **Requirements**

- [ ] Add the `liquidityIncentivePercent` parameter for vaults

**Comment by ra9mls** [comment]
Clone of https://github.com/sora-xor/sora2-network/issues/701
