### ISSUE TITLE
Remove mock-liquidity-source

### ISSUE THREAD

**Issue by KalitaAlexey** [sora-xor/sora2-network#109]
mock-liquidity-source isn't used, but this code requires maintaining.

**Comment by pakrentos** [comment]
- [ ] Dex-api
- [ ] Farming
- [ ] Liquidity proxy
- [ ] TBC
- [ ] price-tools
- [ ] pswap-distribution
- [ ] xor-fee
- [ ] xst
- [ ] runtime
