### ISSUE TITLE
[SPIKE] - OrderBook

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#11]
# Problem
- Users are unable to leave limit orders in an OrderBook and are forced to always trade the market, which can be inefficient and lead to slippage.
- Currently, NFT trading lacks an adequate mechanism such as a marketplace or order book, and users are forced to trade through the XYK pool, which may not always provide the best price or liquidity.

# Solution

To solve the above problems, the creation of an orderBook substrate pallet is required. A trade is executed when the highest bidder bids more than the lowest asker. Liquidity provided on the OrderBook can be used within liquidity proxy as an alternative to XYK pool and TBC.

# Sub-tasks

- [x] #352
- [x] #315
- [x] #333
- [x] #314
- [x] #334 
- [x] https://github.com/sora-xor/sora-docs/issues/45
- Client applications
  - Polkaswap
    - [x] https://github.com/sora-xor/polkaswap-exchange-web/issues/1071

**Comment by Tieumsan** [comment]
Have limit to number open orders submitted and time limited.
Min order size.
Prevent spamming, everything to be on-chain

Use case: MarketPlace (Phygital, NFT)

**Comment by bragov4ik** [comment]
For me such structure seems pretty hard to navigate and understand. Each subtask has its own subtasks, so one needs to visit ~15 pages and remember what happens on the other ones to understand the parts of epic.

Also some tasks seem like a requirement, which means that it's hard to use in our board flow (backlog -> in progress -> review -> test -> closed).

I suggest to do something like this:
```
OrderBook EPIC
├── requirements
│   ├── Compatibility with liquidityProxy #314
│   ├── Global rules for the operations with all order books' entities #334
│   ├── OrderBook history #316
│   └── ...other requirements
└── tasks
    ├── Orders
    │   ├── Market orders #???
    │   ├── Limit orders #333
    │   │   ├── Delete #312
    │   │   │   └── ...
    │   │   ├── Create #307
    │   │   │   └── ...
    │   │   └── Order lifespans #269
    │   └── Matching #192
    ├── Creation of an OrderBook trading pair #311
    └── Deleting an OrderBook pair #331
```
where requirements is a checklist,
tasks is a nested checklist as well, where leaves are actual tasks.
What do you think?

**Comment by bragov4ik** [comment]
> For a precise decomposition, we probably need more levels of nesting.

One approach is to attach external resource with structure for better understanding. However, it's not that useful, since it needs to be kept up-to-date, which does not sound convenient.

Also we might do a combination and link a new issue after a few levels of nesting, so that some local scope and descendant issues are seen in one place.

Or we can leave it as is, since it should not interfere with development process. It only makes harder to see the whole picture, but it can be mitigated with discussion and something else

**Comment by ra9mls** [comment]
Testcases link: https://app.qase.io/project/PSS?suite=44 - in progress
