### ISSUE TITLE
DeFi-R. User Flow optimization

### ISSUE THREAD

**Issue by AndreyKortosov** [sora-xor/sora2-network#1135]
Problem statement:
On the current flow, the user should create an asset, and after the asset is created and minted that asset should be bound to SB token. 

Suggestion:
Due to the project's goal to see how the user will work with regulated assets, the protocol should directly create regulated assets instead of initially creating non-regulated assets and then converting them. This intermediate step is unnecessary.

Definition of Done:

- [ ] The user can create a regulated asset initially.

**Comment by HaidarJbeily7** [comment]
@AndreyKortosov Do we need to have both flows (two steps, one step) or just one flow (one step)?

**Comment by AndreyKortosov** [comment]
@HaidarJbeily7  in DeFi-R project we need only one flow (one step).

**Comment by stefashkaa** [comment]
> @HaidarJbeily7 in DeFi-R project we need only one flow (one step).

We need 2 approaches @AndreyKortosov

**Comment by AndreyKortosov** [comment]
> We need 2 approaches @AndreyKortosov

Okay, got it. @HaidarJbeily7 could you return both flows?

**Comment by HaidarJbeily7** [comment]
@AndreyKortosov @stefashkaa 
I prepared this [PR](https://github.com/sora-xor/sora2-network/pull/1143) which adds support for the second flow.

cc. @vovac12

**Comment by Trezeguet1** [comment]
Verified on dev environment.

https://polkadot.js.org/apps/?rpc=wss://ws.framenode-2.r0.dev.sora2.soramitsu.co.jp#/chainstate
https://exchange.dev.sora2.tachi.soramitsu.co.jp/#/wallet

We added a new extrinsic 'registerRegulatedAsset'

the goal is to have regulated asset registered in the system
we are now supporting 2 flows:

2 steps flow: assets.register -> extendedAssets.regulateAsset
1 step flow: extendedAssets.registerRegulatedAsset
