### ISSUE TITLE
[Tech]:  Asset info update on Subscan for all tokens

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#1189]
### Problem statement

Not enough info on Subscan

### Description

0x0200000000000000000000000000000000000000000000000000000000000000 | XOR | added 
0x0200040000000000000000000000000000000000000000000000000000000000 | VAL | added
0x0200050000000000000000000000000000000000000000000000000000000000 | PSWAP | added
0x0200060000000000000000000000000000000000000000000000000000000000 | DAI |  
0x0200070000000000000000000000000000000000000000000000000000000000 | ETH |  
0x0200080000000000000000000000000000000000000000000000000000000000 | XSTUSD |  
0x0200090000000000000000000000000000000000000000000000000000000000 | XST |  
0x02000a0000000000000000000000000000000000000000000000000000000000 | TBCD |  
0x02000b0000000000000000000000000000000000000000000000000000000000 | KEN |  
0x02000c0000000000000000000000000000000000000000000000000000000000 | KUSD |  
0x02000d0000000000000000000000000000000000000000000000000000000000 | KGOLD |  
0x02000e0000000000000000000000000000000000000000000000000000000000 | KXOR |  
0x02000f0000000000000000000000000000000000000000000000000000000000 | KARMA |  
0x00e8c8923623335128807857dfa38f9212e9803394a2c976e97245d7063bbe10 | TON |  
0x0003b1dbee890acfb1b3bc12d1bb3b4295f52755423f84d1751b2545cebf000b | DOT |  
0x00f40bff02811ad7bd4f84bfa8dc3c79a61e2a17cd55c8418d553e7ffaf596ac | PUSSY |  
0x007f66067c940aeb968b19c8dbf9768447e80c52f73aa175aa8c3936c1bb7e5b | SB |  
0x008bcfd2387d3fc453333557eecb0efe59fcba128769b2feefdd306e98e66440 | CERES |  

.....
https://github.com/subscan-explorer/assets-info
### Definition of Done

Info updated

### Requirements
https://docs.google.com/spreadsheets/d/1LNXqf2fHkx3WpgaH3KwXKRouSnYnSLaXvj4SCIvF4qM/edit?usp=sharing
_No response_

**Comment by WRRicht3r** [comment]
Hello, I sent a request to edit the requirements doc. Also, could you please facilitate the logo images for me (link please) so that I can add them to the request? It will take a proper age (similar to the month it has taken between when the task was open to now) to compile all the images.
cheers.

**Comment by WRRicht3r** [comment]
Logos added wherever necessary. Got in touch with the Subscan team and they're on vacations. They will let me know if there is a solution to bulk upload logo information, in the meantime it is one by one, but will hold off making the files until we have a solution. Tomorrow I will work on the repo and JSON files for the tokens.

**Comment by WRRicht3r** [comment]
In their repo, I submitted the info to Subscan, which is available as a [PR](https://github.com/subscan-explorer/assets-info/pull/87).

**Comment by WRRicht3r** [comment]
PR has been merged on their end, asset info is available. 
Thanks
