### ISSUE TITLE
[Feature]: Vesting and Token locker functions 

### ISSUE THREAD

**Issue by AndreyKortosov** [sora-xor/sora2-network#1195]
# User stories
| As a | I want to | So that |
| --- | --- | --- |
|  Investor of project | I want to buy RLST tokens for my fiat | I will invest my money in a potentially successful project|
| Investor of project | I want to send/sell/swap RLST tokens when they are available | I will get part of my money back with potential profit| 
| Founder/advisor of project |  I want to get RLST tokens | |
| Founder/advisor of project | I want to move/sell/swap my available RLST tokens in 6 months after listing on an exchange| |

# Acceptance criteria

1. The investor buys RLST tokens and enters the SORA accounts on the website.
   1. The team checks and balances and shares their token amount with the investor.
      1. Polkaswap allows tokens to be sent from the corporate wallet to the investor wallet. 
   2. The protocol locks all RLST tokens in the holder wallets for 10 months. 
      1. The protocol uses a Vesting module to lock balances and schedule vesting ways to unlock a specific amount of balance every period of time. [Link](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/vesting) 
   3. Each month the protocol unlocks 10% of the initial number of tokens.
       1. In 10 months all tokens will be unlocked.
       2. A number of the current block + 432000 blocks = block to unlock 10% of the Investor’s tokens.
   4. Polkaswap shows the Investor locked tokens and available tokens.
       1. Polkaswap shows a timer when tokens will be available.
2. The founders and advisors get their RLST tokens on SORA accounts.
   1. The team shares a number of RLST tokens with founders and advisors.
   2. The protocol locks all RLST tokens in the holder wallets for 6 months. 
      1. The protocol uses a Vesting module to lock balances and schedule vesting ways to unlock a specific amount of balance every period of time. [Link](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/vesting)
   3. Each month the protocol unlocks 10% of the initial number of tokens on the founder's and advisor's accounts 6 months after listing on an exchange. 
      1. The team has a notification tool to say about the listing (UI or manually in the blockchain).
         1. The protocol has extrinsic to trigger the process.  
      2. A number of the current block + 2592000 blocks = block to start unlocking tokens on the founder's and advisor's accounts.
      3. In 10 months all tokens will be unlocked.
      4. A number of the current block + 432000 blocks = block to unlock 10% of the founder's and advisor's tokens.
      5. Polkaswap shows the founders' and advisors' locked tokens and available tokens.
         1. Polkaswap shows a timer when tokens will be available.

# Definition of Done

- [x] Implemented vesting module.
- [x] The user can receive locked tokens on account.
- [x] Tokens can locked in 10 months for Investors.
- [x] Tokens can be unlocked each month at 10% for Investors.
- [x] The investor sees locked and unlocked tokens.
- [x] Tokens can be locked for 6 months for founders and advisors.
- [x] Tokens can be unlocked each month at 10% for founders and advisors after 6 months.
- [x] The founder and advisor see locked and unlocked tokens.
- [ ] The Rapido team has the opportunity to notify about the listing token.

**Comment by Trezeguet1** [comment]
Verified and closed as part of task https://github.com/sora-xor/sora2-network/issues/1197
This item has been brought up for discussion in the general chat.
 The Rapido team has the opportunity to notify about the listing token.
