### ISSUE TITLE
[Tech]: Add ORML vesting functionality

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1196]
### Problem statement

It's first step for automatic vesting implementation for #1195

### Definition of Done

- [ ] Move extrinsics [ORML Vesting pallet](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/vesting) to our vesting pallet
- [ ] Add multiasset support

**Comment by ZlayaMorda** [comment]
Parameters values:
**vested_rewards::Config::MaxVestingSchedules = 20**
**vested_rewards::Config::MinVestedTransfer = 1**
**tokens::Config::MaxLocks = 20**
cc. @vovac12 @AndreyKortosov
