### ISSUE TITLE
[Tech]: Additional vesting strategies support

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1197]
### Problem statement

We need to support different vesting strategies as described in #1195

### Definition of Done

- [ ] Investor vesting strategy (the same as default from ORML vesting)
- [ ] Founders/advisors vesting strategy (described in details in #1195)

### Requirements

- Founders/advisors vesting start notification should come from manager account specified during vesting creation

**Comment by Trezeguet1** [comment]
Verified on https://exchange-1564.dev.sora2.tachi.soramitsu.co.jp/#/wallet
The investor will buy tokens for fiat via our partners (FIMA product).

Fixed ✅
We cannot do vesting without the selected BlockNumber, // The block from which the countdown for unlocking begins
![telegram-cloud-photo-size-2-5472050831076483974-y](https://github.com/user-attachments/assets/356f1044-c5c3-4508-a231-b7e08fbcb998)
Fixed ✅
Duplicated assetid here: CommonPrimitivesAssetid32
