### ISSUE TITLE
[Tech]: Automatic vesting support

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#1198]
### Problem statement

To simplify vesting we should be able to make payments automatically

### Definition of Done

- [ ] Add vesting payment schedule
- [ ] (need to clarify) Vesting creating fee adjustment to pay for future automatic payments prior execution
- [ ] (need to clarify) Appropriate limits to avoid too frequent payments

**Comment by Trezeguet1** [comment]
Verified on https://exchange-1564.dev.sora2.tachi.soramitsu.co.jp/#/wallet

**Comment by Trezeguet1** [comment]
(need to clarify) Vesting creating fee adjustment to pay for future automatic payments prior execution
 (need to clarify) Appropriate limits to avoid too frequent payments
