### ISSUE TITLE
Extrinsic for network id fixing for the Bridge

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#120]
Need to change network id for frontend team.

**Comment by vovac12** [comment]
PR https://github.com/soramitsu/sora2-substrate/pull/806

**Comment by Tieumsan** [comment]
@vovac12 is it done ? Is it released ?

**Comment by Tieumsan** [comment]
@vovac12 please check and determine whether we can include it in the next release: 1.9.0

**Comment by vovac12** [comment]
Network id on stage environment is fixed by manual removing of some offchain storage values
