### ISSUE TITLE
[Tech]: Create new dex ID with vXOR as the base asset for pool and order books

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#1222]
### Problem statement

As a DeFi trader I want to put orders (market, limit) and create pools with a vXOR asset as the base asset so that I can better anticipate my returns and manage my trading strategy

### Description

**Preconditions**
User holds vXOR tokens.

**Flow**
Trading pair with vXOR base asset is registered.
User puts an order in the Order Book with vXOR as the quote asset or creates pool with vXOR as a based asset

### Definition of Done

- [x] Users can create trading pair with vXOR as a base asset. (Only for new dex id).
- [x] Users can create XYK pool with vXOR as a base asset. (Only for new dex id).
- [x] Democracy can create Order Book with vXOR as a quote asset (Only for new dex id).

**Comment by stefashkaa** [comment]
New DexId will lead to performance issues in Polkaswap, SORA mobile app and Fearless products.
