### ISSUE TITLE
[Tech]: Rest of vesting part in last schedule

### ISSUE THREAD

**Issue by AndreyKortosov** [sora-xor/sora2-network#1231]
### Problem statement
The vesting solution works only with integers of the period. If after dividing the token amount there is the rest part, this small part will not handled in the schedule.

Part of vesting implementation https://github.com/sora-xor/sora2-network/issues/1195

### Requirements
1. If there is a remainder after dividing the tokens by the periods, add these tokens to the last scheduled action.

### Definition of Done
- [ ] Regardless of the number of periods, all tokens will be distributed
- [ ] If there is a remainder, then the latest schedule by the number of tokens is greater than the rest.

**Comment by Trezeguet1** [comment]
Verified on https://exchange-1564.dev.sora2.tachi.soramitsu.co.jp/#/wallet
