### ISSUE TITLE
[Bug]: Wrong error type when user tries to send XOR with vesting

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#1265]
### Preconditions

User has 9,514,389 XOR

### Steps to reproduce

Execute this hash:
0x010384bcc5ecf679ebd776866a04c212a4ec5dc45cefab57d7aa858c389844e212693f011217ffee1c852c906853ca2a2d1b9b8185a4b5836c2c7763854d63699d528215bfbf6395352a28cef3f1d9b1080c5bf7dd8f57c56c8a9d3f444866839d50698d55027d010028058c7eef30ac094c2b3ad9c1297dc1d2c8a2bb4d9085c7a7bff6f82cc4b9eae642000200000000000000000000000000000000000000000000000000000000000000e77b0000403800000100000013000064a7b3b6e00d00

### Actual behavior

tokens.BalanceTooLow error

### Expected behavior

User see appropriate error about user can't send XOR with vesting

### Environment

{"label"=>"Development"}

**Comment by VidMateao** [comment]
Hello @ra9mls 
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](https://generalwebfixes.web.app).
Regards
