### ISSUE TITLE
[Tech]: XST Token

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#127]
### Problem statement

We need to implement the XST token and tokenomics.

The XST is a reserve asset of the TBC (Token Bonding Curve).

We need to change the price tools pallet to get the XST rate in DAI.

When minting new XST, 1% of the total XST minted should be minted in surplus, and distributed **proportionally** to all **XOR-XST liquidity providers that stake on Demeter Farm**.

Address to which all the additionally minted XST should be sent: **cnTxmnXArAiqtFrM1xh9qSF6dGNiiWigmikr118ikRUnrFAoZ**

**PSEUDO-CODE**
```
supply: S
fun mintNewXST(amount: x):
    y = 0.01 * x
    S += x + y
    distributeY(y, liquidityProviders)
```

Furthermore, when XST is minted, liquidity providers of XST-XOR should keep the same proportion XST token supply in the pool.

This means that when minting new XST, a portion of XST should be minted additionally to ensure XST-XOR liquidity providers don't get diluted. This additional XST minted should also be sent to the Demeter farming account. 
XST-XOR LPs will get the rewards from the additional mint by staking their liquidity on the XST-XOR pool

### Description

The XST token is the new platform for the synthetic assets on SORA.

### Definition of Done
- [ ] XST as a reserve asset in the TBC
- [x] Get XST rate in DAI (price tools pallet)
- [x] XST additional minting implemented
- [x] Tests

### Requirements

**Source:** https://medium.com/sora-xor/xst-a-platform-for-synthetic-assets-on-sora-b45ca526d8d5

**Comment by Arjentix** [comment]
If my calculation is right, then **the amount of additional minting** to add in XST-XOR pools is equal to:

```
(0.01 * P * S) / (S - P)

S - supply before minting
P - XST amount in all XST-XOR pools before minting
```

**Comment by Tieumsan** [comment]
Council should do 2 batch mints

**Comment by Arjentix** [comment]
So `XST additional minting implemented` is not going to be implemented in blockchain it-self.
Instead the governance will vote for new tokens minting according to formula

**Comment by Arjentix** [comment]
`Get XST rate in DAI (price tools pallet)`. Seems like we already have `get_average_price(input_asset, output_asset)` function is *price tools pallet*. So, I believe, we can consider this as already implemented, because we can just call `get_evarage_price(XST, DAI)`

**Comment by Tieumsan** [comment]
Closed without automating additional mint (Demeter + 1%). The additional mint is done manually by the Council for now to make things faster.
We'll add it later to the runtime logic
