### ISSUE TITLE
[Documentation]: Update node version and requirements

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#133]
### Problem statement

The information displayed on the "How to Run a SORA Node" on Medium has some obsolete information. 
https://medium.com/sora-xor/how-to-run-a-sora-testnet-node-a4d42a9de1af

We should update the article and add the guide on the new wiki.

### Definition of Done

- [x] Medium article updated
- [x] "How to Run a Node" guide added to the new SORA wiki

### Methodology

Use the same format as the current guide

### Useful resources

https://medium.com/sora-xor/how-to-run-a-sora-testnet-node-a4d42a9de1af

**Comment by WRRicht3r** [comment]
Hello, could you please provide the parameters that need to be immediately updated in the medium article? I can get started on this asap. 
Thanks

**Comment by Tieumsan** [comment]
SORA node version: 1.4.5

For the Requirements, you would need to ask someone who has its SORA node synced and running (Dmitry from DevOps). 
I don't have it yet on my setup.

**Comment by WRRicht3r** [comment]
Hello, the node version has been updated in the article
Thanks

**Comment by WRRicht3r** [comment]
Follow up- Have set up a call to discuss the new wiki format, will include this guide in the documentation according to the outcome of this meeting
