### ISSUE TITLE
[Feature]: Create new XST-based Synthetic Asset

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#134]
### As a

user

### I want to

propose to create a new XST-based synthetic asset

### So that

I can use new synthetic assets on SORA

### Preconditions

The XST-based synthetic asset does not already exists.

### Flow

1. The user chooses which synthetic asset he/she wants to create based on the list of available assets from oracle data
2. the user sets the fees and spread for the data feeds for buy/sell-price
3. Set fees and spread for different data feeds for buy/sell-price
4. A proposal is created for the SORA community to vote on the proposed new XST-based synthetic asset*
5. If the proposal is accepted, the new XST-based asset is registered on-chain

We should add an extrinsic to enable adjusting the fees and spread for the synthetic asset.

* The list of available data feeds to create a new synthetic asset it derived from the data feeds available from the BandProtocol (https://data.bandprotocol.com/). We filled a form for the Band team, comprising which tickers we are interested in.

### Postconditions

The new XST-based synthetic asset is registered on-chain and usable on the SORA network.

**Comment by Tieumsan** [comment]
Where do the fees go ?
What do we do with the XST used to get XST[...] ?
- Is it burned ?
- Is it sent to a TBC ? 

Should we have a TBC for XST with synthetic assets as reserve assets ?

**Comment by Tieumsan** [comment]
Burn fees, spread=fee amount
settable for each pair
w/ synthetic set via extrinsic fee + spread

**Comment by Tieumsan** [comment]
How do we set/change the fee ? Is it an absolute number, or a percentage of the TX/... ?

**Comment by Tieumsan** [comment]
Will the reference asset be XSTUSD or DAI for the price synthetic assets ?

**Comment by pakrentos** [comment]
Awaiting review

**Comment by pakrentos** [comment]
## How to register synthetic asset 
### Preconditions
- The XST-based synthetic asset does not already exist.
- At least one data feed is enabled in oracle proxy (for now only Band is available).
- The symbol used for synthetic asset creation is not used for existing synthetic asset and is present in oracle-proxy (at least one symbol rate should be relayed)
### Flow
1. Sudo user registers asset with binding to the selected symbol 
### Postconditions
- New asset is registered
- Synthetic asset is enabled (SyntheticAssetEnabled event)
- Synthetic trading pair (XST <-> new asset) is created (if this pair did not exist before)

## How to enable synthetic asset for trade 
### Preconditions
- The synthetic asset is not enabled
- The asset id already exists.
- At least one data feed is enabled in oracle proxy (for now only Band is available).
- XST average price is present in price-tools
- The symbol used for synthetic asset enabling is not used for existing synthetic asset and is present in oracle-proxy (at least one symbol rate should be relayed)
### Flow
1. Sudo user registers asset with binding to the selected symbol 
### Postconditions
- Synthetic asset is enabled (SyntheticAssetEnabled event)
- Synthetic trading pair (XST <-> new asset) is created (if this pair did not exist before)

## How to set reference asset
### Flow
1. Sudo user sets reference asset id
### Postconditions
- Reference asset is set (ReferenceAssetChanged event)

## How to set synthetic asset fee
### Preconditions
- Synthetic asset is enabled
### Flow
1. Sudo user sets synthetic asset fee (fee should be in range [0,1)
### Postconditions
- Synthetic asset fee is changed (SyntheticAssetFeeChanged event)

## How to disable synthetic asset
### Preconditions
- Synthetic asset is enabled
### Flow
1. Sudo user disables synthetic asset
### Postconditions
- Synthetic asset is disabled (SyntheticAssetDisabled event)
- Reference symbol is now available for binding to another asset

## How to trade synthetic assets
### Precondtions
- Synthetic asset is enabled
- Related symbol has actual symbol rate (at most 5 min old for Band data feed)
- XST average price is present in price-tools
### Flow
1. User exchanges synthetics on liquidity proxy
### Postconditions
- Exchange successful

**Comment by pakrentos** [comment]
## How to register synthetic asset 
### Preconditions
- The XST-based synthetic asset does not already exist.
- At least one data feed is enabled in oracle proxy (for now only Band is available).
- The symbol used for synthetic asset creation is not used for existing synthetic asset and is present in oracle-proxy (at least one symbol rate should be relayed)
### Flow
1. Sudo user registers asset with binding to the selected symbol 
### Postconditions
- New asset is registered
- Synthetic asset is enabled (SyntheticAssetEnabled event)
- Synthetic trading pair (XST <-> new asset) is created (if this pair did not exist before)

## How to enable synthetic asset for trade 
### Preconditions
- The synthetic asset is not enabled
- The asset id already exists.
- At least one data feed is enabled in oracle proxy (for now only Band is available).
- XST average price is present in price-tools
- The symbol used for synthetic asset enabling is not used for existing synthetic asset and is present in oracle-proxy (at least one symbol rate should be relayed)
### Flow
1. Sudo user registers asset with binding to the selected symbol 
### Postconditions
- Synthetic asset is enabled (SyntheticAssetEnabled event)
- Synthetic trading pair (XST <-> new asset) is created (if this pair did not exist before)

## How to set reference asset
### Flow
1. Sudo user sets reference asset id
### Postconditions
- Reference asset is set (ReferenceAssetChanged event)

## How to set synthetic asset fee
### Preconditions
- Synthetic asset is enabled
### Flow
1. Sudo user sets synthetic asset fee (fee should be in range [0,1)
### Postconditions
- Synthetic asset fee is changed (SyntheticAssetFeeChanged event)

## How to disable synthetic asset
### Preconditions
- Synthetic asset is enabled
### Flow
1. Sudo user disables synthetic asset
### Postconditions
- Synthetic asset is disabled (SyntheticAssetDisabled event)
- Reference symbol is now available for binding to another asset

## How to trade synthetic assets
### Precondtions
- Synthetic asset is enabled
- Related symbol has actual symbol rate (at most 5 min old for Band data feed)
- XST average price is present in price-tools
### Flow
1. User exchanges synthetics on liquidity proxy
### Postconditions
- Exchange successful
