### ISSUE TITLE
[Bug]: PSWAP Rewards claiming

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#145]
### Preconditions

User has earned PSWAP from contributing to crowdloans.

### Steps to reproduce

1. User claims his PSWPA rewards on Polkaswap

### Actual behavior

The PSWAP rewards disappear and the user does get his PSWAP rewards

### Expected behavior

The user receives the PSWAP rewards he/she claimed to his wallet.

### Environment

{"label"=>"Production"}

### Additional context

The bug should already be fixed, we need to include it in the next runtime upgrade.

**Comment by vovac12** [comment]
https://github.com/soramitsu/sora2-substrate/pull/670
