### ISSUE TITLE
[Tech]: XOR-XST - pool double strategic APY

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#148]
### Problem statement

As part of the new Platform for Synthetics, we introduce the new XST token. To incentivise the community to provide liquidity in XOR-XST, we make the strategic bonus APY for XOR-XST liquidity providers double.

### Definition of Done

- [x] Double strategic bonus APY for the XOR-XST pool
- [ ] Tests

**Comment by ra9mls** [comment]
Waiting for prod
