### ISSUE TITLE
[SPIKE] - Investigate XCM

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#16]
Research XCM
https://wiki.polkadot.network/docs/learn-crosschain

The main goal is to check how can KSM be transferred from Kusama to SORA parachain and from SORA parachain to Kusama

**Comment by Tieumsan** [comment]
**XCM – The Backbone Of A Multichain Future**: https://www.youtube.com/watch?v=uN64X2Yr31M

**Comment by bragov4ik** [comment]
Some findings https://soramitsu.atlassian.net/l/cp/T64Grz0v

**Comment by Tieumsan** [comment]
**Definition of Done**
- What is the difference between HRMP and XCM/XCMP ?
- How do HRMP and XCM/XCMP interact ?
- What do we need to implement to support XCM v3 ?
- What functionality is enabled with XCM v3 ?
- Is there any additional implementation required to support specific functionality, not supported by a basic implementation of XCM ? (e.g.: token support)
- Do XCM enable communication between SORA Parachain <-> Other parachains and also between SORA Parachain <-> SORA Mainnet, or will the implementation need to be different ?

@N1ghtStorm @bgodlin
