### ISSUE TITLE
[Bug]: Wrong quote calculation on test env for XOR-ETH pair

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#162]
### Steps to reproduce

1. Open https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.framenode-1.v1.tst.sora2.soramitsu.co.jp#/rpc
2. Choose liquidityProxy.quote
3. Input asset ID's 
0x0200000000000000000000000000000000000000000000000000000000000000
0x0200070000000000000000000000000000000000000000000000000000000000
amount: 1000000000000000000 (1 XOR)
4. Execute this RPC

### Actual behavior

liquidityProxy.quote: Option<LPSwapOutcomeInfo>
{
  amount: 280.6150 fXOR
  fee: 3.0000 mXOR
  rewards: []
  amountWithoutImpact: 0
}

### Expected behavior

//Try to do the same on frontend side.
//https://exchange.tst.sora2.tachi.soramitsu.co.jp/#/swap
//Result should be about 1 XOR / 0.136038116729256209 ETH-
Frontend side is shows via DEXID=1 for this pair
So, you should need to check poolXYK.Reserves for XOR-ETH pair
You can see 
      8,982,524,342,991,979,557,941
      10,858,620,000,173,812,381
After calculations you can see about 1 XOR to 0,001113272839572 ETH 

We had checked balances after swap. 
Frontend doesn't use rpc calls because contains internal realisation of quote function.

### Environment

{"label"=>"Test"}

**Comment by pakrentos** [comment]
This problem is related to migration procedure, which was conducted twice. After one swap, the ratio was fixed
