### ISSUE TITLE
[Tech]: Check the code for hardcoded old fees

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#171]
### Problem statement

We found an issue https://github.com/sora-xor/sora2-network/issues/170 it's related with fees amount which might be hardcoded.
Need to check for the possibility of repeating the problem elsewhere.

### Definition of Done

- [x] No hardcoded fees
- [x] Hardcoded fees replaced with baseFee and FeeMultiplier

**Comment by Tieumsan** [comment]
**Needs analysis:**

- Should all hardcoded fees be replaced in the same way ?
- Are different types of fees do we have ? (baseFee, LPfee, XSTfee, ...)
