### ISSUE TITLE
[Bug][Investigate]:  2 of 3 peers went down on PROD bridge

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#176]
### Steps to reproduce

When i requested for signatures

I saw one signature

Then 1-2 mins later, i saw 2nd signature then got 3rd one

### Actual behavior

https://sora.subscan.io/block/7862593

### Expected behavior

All 3 peers are working.

### Environment

{"label"=>"Production"}

### Additional context

![image](https://user-images.githubusercontent.com/17094492/201039351-feed911b-5cbc-4d77-b3b2-27e998cb7861.png)

**Comment by vovac12** [comment]
The peer nodes were upgraded to the node version with memory leak and did not work for a while due to out of memory
