### ISSUE TITLE
[Support]: User Lost transaction Claim

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#187]
### Problem statement

One of our community member (@burekmaker) tried to bridge 1k DAI to Ethereum network 487 days ago but something failed and polkaswap.io didn't pop his metamask for TX. His bridge request looks unclaimed.

Problem is his current signatures(v,r,s values) are invalid since we changed the bridge contract. 

If you check it and see it unclaimed, we could recreate signatures for him so we can go without governance mint.

### Description

- His SORA account: https://sora.subscan.io/account/cnTyykJBfrH9pH3av8rebzd5aSJ28qJXYTEi9y9Uk4P6TN6H5 
- His ETH account: https://etherscan.io/txs?a=0x8d5ba2b764356ddc9997fed94dcf83367e8a10a2&p=8 
- His bridge hash: 0x595b2602b234a9a233314923874c2bff4fc6ca2148abee1ec7f7608b5f374caf

### Definition of Done

- [x] Determine whether the claim is valid (check unclaimed TX on bridge)
- [ ] If claim is valid (TX unclaimed), recreate signatures for the user

**Comment by pakrentos** [comment]
Funds will be reclaimed through https://sora.subscan.io/extrinsic/0x4fcbfeebfb365041df7373b3ed3e45e6e534efffcd837fb32c595eaf44c9b22f
