### ISSUE TITLE
OrderBook. Matching

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#192]
# Description

The pallet will automatically match buy and sell orders based on price and time priority. When a match is found, the pallet will lock the NFTs and funds involved in the trade and transfer them between the users' accounts. The order book will be updated to reflect the trade, and any expired orders will be removed.

# Preconditions

- There are orders to match
  - Previously at least one #203 and #204 were created for a common pair (see #311)

# Requirements

- [x] #329
- [x] #330
- [x] https://github.com/sora-xor/sora2-network/issues/465

# Postconditions

The matching algorithm for limit orders has effectively matched the bid and ask limit orders, resulting in partial or complete execution of some of them.

**Comment by bragov4ik** [comment]
Which price is chosen for the executed trade? For example, if there is a sell order for 10 XOR and a buy order for 15 XOR, how their match should be handled?
