### ISSUE TITLE
Storage root must match that calculated (substrate:v0.1.7)

### ISSUE THREAD

**Issue by jimiflowers** [sora-xor/sora2-network#2]
docker[24013]: ====================
docker[24013]: Version: 0.1.0-d529c21-x86_64-linux-gnu
docker[24013]:    0: sp_panic_handler::set::{{closure}}
docker[24013]:    1: std::panicking::rust_panic_with_hook
docker[24013]:              at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/std/src/panicking.rs:595:17
docker[24013]:    2: std::panicking::begin_panic::{{closure}}
docker[24013]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
docker[24013]:    4: std::panicking::begin_panic
docker[24013]:    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::final_checks
docker[24013]:    6: tracing::span::Span::in_scope
docker[24013]:    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
docker[24013]:    8: <framenode_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,framenode_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_tx_version::CheckTxVersion<framenode_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<framenode_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<framenode_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<framenode_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<framenode_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<framenode_runtime::Runtime>)>>>>::execute_block
docker[24013]:    9: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
docker[24013]:   10: std::thread::local::LocalKey<T>::with
docker[24013]:   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
docker[24013]:   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
docker[24013]:   13: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
docker[24013]:   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
docker[24013]:   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
docker[24013]:   16: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
docker[24013]:   17: sp_api::runtime_decl_for_Core::execute_block_call_api_at
docker[24013]:   18: sp_api::Core::execute_block_with_context
docker[24013]:   19: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
docker[24013]:   20: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
docker[24013]:   21: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
docker[24013]:   22: <alloc::boxed::Box<dyn sp_consensus::block_import::BlockImport<B>+Transaction = Transaction+Error = sp_consensus::error::Error+core::marker::Sync+core::marker::Send> as sp_consensus::block_import::BlockImport<B>>::import_block
docker[24013]:   23: sp_consensus::import_queue::import_single_block_metered
docker[24013]:   24: futures_util::future::future::FutureExt::poll_unpin
docker[24013]:   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
docker[24013]:   26: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
docker[24013]:   27: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
docker[24013]:   28: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
docker[24013]:   29: <sc_service::task_manager::WithTelemetrySpan<T> as core::future::future::Future>::poll
docker[24013]:   30: std::thread::local::LocalKey<T>::with
docker[24013]:   31: futures_executor::local_pool::block_on
docker[24013]:   32: tokio::runtime::task::core::Core<T,S>::poll
docker[24013]:   33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
docker[24013]:   34: tokio::runtime::task::raw::poll
docker[24013]:   35: tokio::runtime::blocking::pool::Inner::run
docker[24013]:   36: tokio::runtime::context::enter
docker[24013]:   37: std::sys_common::backtrace::__rust_begin_short_backtrace
docker[24013]:   38: core::ops::function::FnOnce::call_once{{vtable.shim}}
docker[24013]:   39: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
docker[24013]:              at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/alloc/src/boxed.rs:1546:9
docker[24013]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
docker[24013]:              at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/alloc/src/boxed.rs:1546:9
docker[24013]:       std::sys::unix::thread::Thread::new::thread_start
docker[24013]:              at rustc/f98721f886ab52d32d622ad0a46216ad03f3e525/library/std/src/sys/unix/thread.rs:71:17
docker[24013]:   40: start_thread
docker[24013]:   41: clone
docker[24013]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /opt/rust/registry/src/github.com-1ecc6299db9ec823/frame-executive-3.0.0/src/lib.rs:405

**Comment by takemiyamakoto** [comment]
The chainspecs are different from the 0.1.7 testnet. This will be updated here in the future so it will work with testnet and production.

**Comment by takemiyamakoto** [comment]
There also seem to be some nuances between running from source vs. running from the docker image, so this also seems to be an issue as well.

For the tokio errors, these can mostly be ignored

**Comment by KalitaAlexey** [comment]
This particular error can be fixed by adding `--execution Wasm`.

**Comment by jimiflowers** [comment]
> 
> 
> There also seem to be some nuances between running from source vs. running from the docker image, so this also seems to be an issue as well.
> 
> For the tokio errors, these can mostly be ignored

Ok, I understand. The problem is that the validator is left out of the validation process every time the error occurs.

@KalitaAlexey the process is runnig with that option.

**Comment by KalitaAlexey** [comment]
It's strange. We never faced this issue with `--execution Wasm`.

**Comment by jimiflowers** [comment]
As this version is outdated, I proceed to close the issue.
