### ISSUE TITLE
Add Clippy or other linter to the CI

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#20]
Add Clippy or other rust linter https://github.com/rust-lang/rust-clippy  to the backend build.

**Comment by Tieumsan** [comment]
- [ ] Check if Clippy works w/ Substrate
- [ ] Define which functionalities we want from Clippy
- [ ] Ask DevOps to set it up

**Comment by f33r0** [comment]
Ready, developers need to test it and see if it is convenient to use it.

**Comment by f33r0** [comment]
https://github.com/soramitsu/sora2-substrate/pull/841 linter is here
