### ISSUE TITLE
[Feature]: Swap & Send (batch)

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#208]
### As a

Salary payer

### I want to

Swap from one asset to another and send the target asset to a set of addresses and amount pairs

### So that

I can easily pay for salaries

### Preconditions

The user has enough funds to swap from the origin asset to the target asset.
There is enough liquidity of the target asset to swap to.
The set of addresses are valid.
The sum to be sent is equal to the sum to be swapped.

### Flow

1. The user selects the origin asset and the target asset
2. The user selects the amount to swap FROM, OR to swap TO
3. The user inputs the list of addresses to send the target asset to, with a dedicated amount for each receiver address
4. The system swaps from the origin asset to the target asset and sends the amounts to each address in one batch

### Postconditions

The origin asset has been swapped to the target asset.
Each receiving address has received the amount of target asset.

**Comment by Tieumsan** [comment]
@bgodlin we will need documentation for this for the ADAR team

**Comment by ra9mls** [comment]
We should add this event to subquery.
