### ISSUE TITLE
[Bug]: LiquidityProxy.quote FilterMode works bad with multi Forbidding

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#218]
### Preconditions

XOR-VAL (example) pool should be created with reserves.
### Steps to reproduce

1. Open dev apps RPC LiquidityProxy.quote
2. Input pair XOR-VAL (for example)
3. Forbid markets XST and TBC
4. Submit RPC

### Actual behavior

User sees <none>

### Expected behavior

He should sees quote with XYK market cuz other forbidden.

### Environment

{"label"=>"Development"}

**Comment by pakrentos** [comment]
Looks like it should work like that 
```
    impl liquidity_proxy_runtime_api::LiquidityProxyAPI<
        Block,
        DEXId,
        AssetId,
        Balance,
        SwapVariant,
        LiquiditySourceType,
        FilterMode,
    > for Runtime {
        fn quote(
            dex_id: DEXId,
            input_asset_id: AssetId,
            output_asset_id: AssetId,
            amount: BalanceWrapper,
            swap_variant: SwapVariant,
            selected_source_types: Vec<LiquiditySourceType>,
            filter_mode: FilterMode,
        ) -> Option<liquidity_proxy_runtime_api::SwapOutcomeInfo<Balance, AssetId>> {
            if LiquidityProxy::is_forbidden_filter(&input_asset_id, &output_asset_id, &selected_source_types, &filter_mode) {
                return None;
            }
```

`is_forbidden_filter` checks if one of the assets is available on tbs and at the same time if the TBC is present in filter. If asset is present on TBC and TBC is forbidden, then rpc returns None
