### ISSUE TITLE
[Doc]: Substrate bridge

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#224]
### Problem statement

We want to come up with documentation for the Substrate bridge.
Communicate with frontend team and backend team to define a proper documentation to support both the teams in Soramitsu and the Builders.

### Definition of Done

- [ ] Substrate bridge documentation added to the wiki

**Comment by N1ghtStorm** [comment]
Added an article about interaction with relay chains and parachain https://soramitsu.atlassian.net/wiki/spaces/SB/pages/4014866588/SORA2+-+Parachains+Relaychain+interaction

**Comment by N1ghtStorm** [comment]
Added an article about bridge architecture 
https://soramitsu.atlassian.net/wiki/spaces/SB/pages/3703963651/Bridge+architecture

**Comment by bgodlin** [comment]
Duplicates https://github.com/sora-xor/sora-docs/issues/7
