### ISSUE TITLE
[Spike]: PSWAP APY Rewards implementation

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#235]
### Problem statement

We want to ensure the implementation for the calculation of PSWAP rewards is correct.

### Definition of Done

- [ ] Check implementation
- [ ] Fix implementation if needed

### Methodology

Check article on theoretical explanation of PSWAP rewards
https://medium.com/polkaswap/pswap-rewards-1-polkaswap-liquidity-reward-farming-3e045d71509

**Comment by pakrentos** [comment]
PR: https://github.com/soramitsu/sora2-substrate/pull/870
