### ISSUE TITLE
[Bug]: Investigate. The quote calculation for TBC occurs only in the withDesiredOutput direction, but in the withDesiredInput direction the result is none.

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#240]
### Steps to reproduce

1. Open RPC liquidityProxy.quote
2. Fill the assets id's 
0x0200060000000000000000000000000000000000000000000000000000000000
0x0200000000000000000000000000000000000000000000000000000000000000
3. Amount 1000000000000000000
4. Swap desired variant: WithDesiredOutput
5. Execute call to receive amount 
```
 liquidityproxy.quote: option<lpswapoutcomeinfo>
{
  amount: 32.4839 MXOR
  fee: 3.0090 mXOR
  rewards: [
    {
      amount: 42.3918 mXOR
      currency: 0x0200050000000000000000000000000000000000000000000000000000000000
      reason: BuyOnBondingCurve
    }
  ]
}
```
7. Then change Swap desired variant: WithDesiredInput
8. Insert received amount 324839000000000000000000000000
9. Execute call 

### Actual behavior

None

### Expected behavior

User should receive calculated amount to swap 1 dai to 324839000000000000000000000000 XOR

### Environment

{"label"=>"Development"}

### Additional context

![tbcInput](https://user-images.githubusercontent.com/17094492/214028813-ee3eb00a-162b-4246-9d1b-d4bd881b97f9.jpg)
![tbcOutput](https://user-images.githubusercontent.com/17094492/214028831-10fb0bcc-ffde-4831-b8a3-6569a38d45ae.jpg)

**Comment by Tieumsan** [comment]
Closed with solved
