### ISSUE TITLE
[Tech]: Support multi asset output in liquidityProxy.swapTransferBatch

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#246]
### Problem statement

We need to sign and send several extrinsics for each output asset

### Description

This extrinsic need to get asset_id for each receiver and send desired amount of given asset to receiver. 

### Definition of Done

- [x] Implement new behavior
- [x] Update tests
- [x] Check it locally

### Requirements

To improve performance we should make only 1 swap for each asset

**Comment by pakrentos** [comment]
PR: https://github.com/soramitsu/sora2-substrate/pull/889

**Comment by ra9mls** [comment]
DexID needs to be selected for each **LiquidityProxyBatchReceiverInfo**
Will be better to have this extrinsic XOR less

**Comment by ra9mls** [comment]
Checked on console logs in apps. But waiting the definitions from polkadot.
![image.png](https://images.zenhubusercontent.com/62bbde011ca04a42bf2c5247/87b16674-a38d-45ab-8227-f8bb653bf891)
![image.png](https://images.zenhubusercontent.com/62bbde011ca04a42bf2c5247/92fbe685-f77d-416f-8252-80a1c84df47e)

**Comment by ra9mls** [comment]
Found a bug, waiting the fix.

**Comment by ra9mls** [comment]
Fixed now.
Have restriction on this extrinsic.
We can't swap AssetA to AssetB+AssetB to same account twice in single tx.
Adar team was notified.
