### ISSUE TITLE
[Tech]: Add RMRK token to bridge

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#252]
### Problem statement

As part of the expansion of the SORA ecosystem, we want to add the RMRK to our bridges.

**Asset Name**: RMRK
**Asset Symbol**: RMRK
**AssetID (SORA)**: 0x00d8704f17ffef6f1b1831a66a8f9b58d930f4d3deb9100f82571f6dab278f2a
**Decimals**: 10 (SORA has 18 decimals, we should be sure it works in/out of the ecosystem if we keep 18)
**Icon**: https://statemine.statescan.io/imgs/icons/asset/rmrk.svg

### Definition of Done

- [x] RMRK Token added to the whitelist (https://github.com/sora-xor/polkaswap-token-whitelist-config)
- [x] RMRK Token registered on HASHI bridge

**Comment by stefashkaa** [comment]
@Tieumsan https://github.com/sora-xor/polkaswap-token-whitelist-config/pull/38
