### ISSUE TITLE
[Tech]: Return lost MM rewards

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#253]
### Problem statement

When we removed the Market Maker Countdown, some users saw their rewards disappear.
To remedy that, we created a new extrinsic to return the rewards: `vestedRewards.updateRewards`

We need to get the list of users for whom the rewards disappeared, along with the amount of rewards, in PSWAP.

### Definition of Done

- [x] Get list of users for whom rewards disappeared and corresponding amount for each user
- [x] Create proposal to return the rewards to those users

**Comment by vovac12** [comment]
Here is list of lost rewards and script to fetch it
[https://app.zenhub.com/files/356546020/3d37fc6c-a08b-4e81-aa26-f9b4863905f9/download](https://app.zenhub.com/files/356546020/3d37fc6c-a08b-4e81-aa26-f9b4863905f9/download)
