### ISSUE TITLE
[Feature]: Show route to the liquidityProxy.quote RPC

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#255]
### As a

Developer / User

### I want to

Know the asset routing for my swap quote

### So that

I can easily display the swap routing in the UI

### Preconditions

User has inputted the parameters `inputAssetId`, `outputAssetId`, `amount`.

The user/system has sent the RPC call `liquidityProxy.quote`

### Flow

1. The user has entered the parameters `inputAssetId`, `outputAssetId`, `amount`
2. The external system (client application) send the RPC call `liquidityProxy.quote(inputAssetId, outputAssetId, amount)`
3. The system (blockchain) returns the swap routing.
  - object name: `route`
  - type: [string]
  - string format: AssetId in form of "0x..."

**Comment by ra9mls** [comment]
![image.png](https://images.zenhubusercontent.com/62bbde011ca04a42bf2c5247/104c381b-77e1-44df-8cb0-51ff324211b5)

**Comment by ra9mls** [comment]
Nodes need to be updated
