### ISSUE TITLE
Enable SB APY on XSTUSD-based pools

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#261]
https://github.com/sora-xor/sora2-network/blob/c69ee70022fa27d0cabfba0e4bc7dee4f261bf2b/pallets/farming/src/lib.rs#L75
We need to remove this check and add XSTUSD based pools via migration

Ensure the same amount of rewards are distributed for both DEXids

**Comment by Tieumsan** [comment]
Don't return rewards from past, enable SB APY on XSTUSD-based pools

**Comment by Tieumsan** [comment]
Ensure same amount of rewards are distributed for both DEXids
