### ISSUE TITLE
[SPIKE] - Return rewards planned for XSTUSD-based pools

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#290]
#### Problem Statement
Some users though they would get SB rewards form providing liquidity to XSTUSD-based pools. This was not initially implemented, so users did not get the rewards.

_______
Don't return rewards from past, enable SB APY on XSTUSD-based pools

_Originally posted by @Tieumsan in https://github.com/sora-xor/sora2-network/issues/261#issuecomment-1425608576_
            
#### Requirements
- How do we return the rewards to users ?
- Where do users get the returned rewards ?
- How much rewards do we return ? (from what date)

Rewards should be vested

**Comment by Tieumsan** [comment]
Need decision on terms for returning rewards

**Comment by vovac12** [comment]
Rewards from 8035061 to 9479000 block

- Rewards only for XOR based pools (current implementation): 251250000 PSWAP

- Rewards for XSTUSD pools - rewards for XOR pools (as if XSTUSD pool rewards were enabled initially): 2813018 PSWAP

- XSTUSD pools rewards without XOR pools (as on frontend): 250625000 PSWAP
