### ISSUE TITLE
[Feature]: Add additional fee to swap batch extrinsic

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#301]
### As a

ADAR

### I want to

Take fees from batch swaps

### So that

-

### Flow

1. User calls swap_batch_transfer extrinsic
2. 0.75% of input asset goes to ADAR account (currently unknown)

**Comment by vovac12** [comment]
ADAR account should be constant. We can add it to Config of liquidity-proxy pallet

**Comment by pakrentos** [comment]
#325 
TODO:
- [ ] Add ADAR commission to swap_transfer_batch
- [ ] Refactor
- [ ] Add new tests

**Comment by pakrentos** [comment]
#325 
TODO:
- [ ] Add ADAR commission to swap_transfer_batch
- [ ] Refactor
- [ ] Add new tests

**Comment by pakrentos** [comment]
Duplicate of the #323
