### ISSUE TITLE
[Feature]: ADAR fees

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora2-network#323]
# Problem
The ADAR developer is not receiving any fees currently, which limits their profit potential.

# Solution
To address this problem, we need to implement automatic deduction of fees from transactions made through the dapp. By deducting a percentage fee from the transfer value (with no slippage and network fee included), the dapp developer can have an additional profit channel.

# Requirements

- [ ] Blockchain automatically deducts a percentage fee from each transaction made through the dapp.
  - [ ] #324
- [ ] The percentage fee is 0.75%
- [ ] The fees collected should be sent to a specific wallet address `cnWUANWMTvvPZfnwzPHJnvTzLXGFzp1qKk4y8WWFgLjgZEXdR`
- [ ] The receival address and fee should be changeable only via a runtime upgrade. That way the system will be secure and prevent any potential attacks or unauthorized access.
- [ ] The fee deduction should be done with no slippage and network fee included.

**Comment by pakrentos** [comment]
PR: #325
