### ISSUE TITLE
[Bug]: cheap tbcd problem

### ISSUE THREAD

**Issue by Nolan730** [sora-xor/sora2-network#326]
### Steps to reproduce

1. check price for buying tbcd
2. sell tbcd for anything
3. check price for buying tbcd again

### Actual behavior

cheap buy price for tbcd after someone sell tbcd

### Expected behavior

tbcd price shouldnt be cheaper when someone sells tbcd

### Environment

{"label"=>"Production"}

### Additional context

Edit:
https://github.com/sora-xor/sora2-network/blob/faabc97e493c20732c8232fc0ccb2193485870ce/pallets/multicollateral-bonding-curve-pool/src/lib.rs#L1070
My first thought is wrong. But its definitly related to sell_price function and cnTQ1kbv7PBNNQrEb1tZpmK7dm1HKXnwheGZ4iorLCGF6gRzr this tech wallet. This wallet recieves some tbcd after someone sells tbcd and when this amount goes bigger, sell_price function gives cheaper price

**Comment by takemiyamakoto** [comment]
Looks like a bug. I pointed this out to the team

**Comment by Nolan730** [comment]
@takemiyamakoto as we talked about this topic, this is more like unintended side effect instead of a bug. For other people, this is the reason:
System sells %20 of sold tbcd into xyk pool(xor-tbcd). As a result this sell makes pool unbalanced and offers cheaper tbcd. Good luck on arbitrage race.
