### ISSUE TITLE
Progressive fee scale

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora2-network#348]
# Description

The commission value is chosen relative to the set expiration date (see #271). The longer the term, the higher the fee. Within current version the following calculation will take place:

```math
maxFee*(1 - \frac{maxExpirationTimestamp-setExpiration}{maxExpirationTimestamp})
```

# Requirements

- [ ] Implement the fee scaling based on percentage

**Comment by wer1st** [comment]
Fee proposals:
- The fee to place a limit order should be lower than general network fee (0.07 XOR). It is a standard practice that market makers pay less than takers. And if a taker pays 0.07 XOR for swap, a maker could pay maximum 0.035 XOR. The lower fee is a motivation for users to exchange their liquidity by limit orders.
- The fee should be flexible in proportion to a lifetime of a limit order. I suggest to divide it (0.035 XOR) into 2 parts: constant part is 0.02 XOR independent of lifetime and flexible part is 0.015 XOR that calculated proportionally on lifetime by the formula above. It allows to avoid placing almost free limit orders with min possible lifetime.
- User can cancel their limit orders for free. In practice it means that cancellation of limit order takes 0 fee if it executes correctly and takes standard fee 0.07 XOR if some error occurs. When a limit order expires it is also automatically cancelled for free.

**Comment by wer1st** [comment]
Zero fees for cancellation of limit orders will be implemented in #652

**Comment by ra9mls** [comment]
@wer1st please check this table
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1uQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4ef9d7370ec0bdd2b6edb1ca14cf7fac23a96cc/Screenshot%202023-11-06%20at%2016.46.08.png)

**Comment by wer1st** [comment]
@ra9mls No, wrong order.
0 days - 0 flex fee - 0.02 const fee - 0.02 total
30 days - 0.015 flex fee - 0.02 const fee - 0.035 total

**Comment by ra9mls** [comment]
Test case: https://app.qase.io/case/PSS-158
