### ISSUE TITLE
Max amount of simultaneously opened orders

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora2-network#349]
# Description

The blockchain must keep a counter of open orders between in orderbooks. If user's order exceeds the maximum allowable value for the number of simultaneously open orders, it should not be created. Each order book will have the following parameters:

`MaxOpenedLimitOrdersPerUser`
`MaxLimitOrdersForPrice`
`MaxSidePriceCount`

The maximum amount of open orders will have the following calculation formula:

`MaxSidePrices` * `MaxLimitOrdersForPrice` * 2

**Comment by wer1st** [comment]
Decided:

- We restrcit the max count of simultaneously opened orders in **one** order book
- The value is a const and could be changed only by runtime upgrade
