### ISSUE TITLE
Write article about new feature flags

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#355]
- [x] General description
- [x] Detailed description

**Comment by Tieumsan** [comment]
@wer1st we can add this to the SORA wiki - https://wiki.sora.org/pallets.html
cc. @WRRicht3r @vovac12

**Comment by wer1st** [comment]
> @wer1st we can add this to the SORA wiki - https://wiki.sora.org/pallets.html
> 
> cc. @WRRicht3r @vovac12 

It is more related to dev process than pallets description
