### ISSUE TITLE
Migrate to Substrate 4

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#39]
Migrate to the substrate 4 (https://github.com/paritytech/substrate )

Currently we’re waiting for the release of the new substrate.

**Precondition:**
Substrate 4 released

**Definition of Done:**
Network migrated to the substrate 4

All environments updated

**Env:**
https://soramitsu.atlassian.net/wiki/spaces/PLS/pages/3526787079/Substrate+4+dev

**Comment by ra9mls** [comment]
Continue testing on DEV4 network. Will produce on DEV env soon.
