### ISSUE TITLE
[Tech debt]: Use DexInfoProvider instead of pallet

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#392]
### Problem statement

We call functions directly from pallets. It is necessary to use traits in Config for these calls.
One of such using is getting dex info from `dex-manager` pallet.

### Description

Replace all calls related to dex info with using `DexInfoProvider` trait.

Note:
Search `// TODO: #392 use DexInfoProvider instead of dex-manager pallet` comment in the code. It helps to find necessary places.

### Definition of Done

1. All components get dex info from `DexInfoProvider`
2. All tests passed

**Comment by Tieumsan** [comment]
@wer1st what is the status of this task ? It's merged but still in _Ready for Test_.

**Comment by wer1st** [comment]
> @wer1st what is the status of this task ? It's merged but still in _Ready for Test_.

Usually we move tasks to the column Ready for Test after merging in develop and QA can test it after that.
However, this task cannot be tested by QA, will close it.
