### ISSUE TITLE
[Tech debt]: Use AssetInfoProvider instead of pallet

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#395]
### Problem statement

We call functions directly from pallets. It is necessary to use traits in Config for these calls.
One of such using is getting asset info from `assets` pallet.

### Description

Replace all calls related to asset info with using `AssetInfoProvider ` trait.

Note:
Search `// TODO: #395 use AssetInfoProvider instead of assets pallet` comment in the code. It helps to find necessary places.

### Definition of Done

1. All components get asset info from `AssetInfoProvider` 
2. All components use DexInfoProvider instead of direct using `AssetInfos` and `AssetOwners` storages.
3. All tests passed

**Comment by Tieumsan** [comment]
@vovac12 has this issue already been included in a release ?
