### ISSUE TITLE
OrderBook. CRUD operations permissions

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora2-network#400]
<table class="c20">
      <tr class="c13">
        <td class="c12" colspan="2" rowspan="2">
          <h1 class="c21" id="h.m9vhjvp9v18w">
            <span class="c0">&#9196; Asset type</span>
          </h1>
        </td>
        <td class="c24" colspan="3" rowspan="1">
          <h1 class="c21" id="h.swtin4vpkm0k"><span class="c16">CRUD</span></h1>
        </td>
      </tr>
      <tr class="c13">
        <td class="c3" colspan="1" rowspan="1">
          <h1 class="c21" id="h.swtin4vpkm0k-6">
            <span class="c0">Creation</span>
          </h1>
        </td>
        <td class="c6" colspan="1" rowspan="1">
          <h1 class="c21" id="h.swtin4vpkm0k-7">
            <span class="c0">Parameter modification</span>
          </h1>
        </td>
        <td class="c6" colspan="1" rowspan="1">
          <h1 class="c21" id="h.h3rggpr2qcmr">
            <span class="c0">Status modification and removal</span>
          </h1>
        </td>
      </tr>
      <tr class="c15">
        <td class="c11" colspan="1" rowspan="2">
          <p class="c10"><span class="c9">Regular asset</span></p>
        </td>
        <td class="c4" colspan="1" rowspan="1">
          <p class="c10"><span class="c9"><a class="c25"
                href="https://github.com/sora-xor/polkaswap-token-whitelist-config/blob/master/whitelist.json"
                >Default</a></span></p>
        </td>
        <td class="c3" colspan="1" rowspan="1">
          <p class="c10">
            <span class="c8"
              >Automatically on runtime upgrade from the whitelisted technical
              account</span
            >
          </p>
          <p class="c10"> Default parameters:
            <li class="c5 li-bullet-0"><span class="c8">Price step: 0.00001 XOR</span></li>
            <li class="c5 li-bullet-0"><span class="c8">Volume step: 0.00001</span></li>
          </p>
        </td>
        <td class="c6" colspan="1" rowspan="1">
          <ul class="c18 lst-kix_gnd1hip7nte-0 start">
            <li class="c5 li-bullet-0"><span class="c8">Asset owner</span></li>
            <li class="c5 li-bullet-0"><span class="c8"><a
                href="https://github.com/sora-xor/sora2-network/issues/413"
                >Root (democracy) OR Technical committee</a></span></li>
          </ul>
        </td>
        <td class="c6" colspan="1" rowspan="1">
          <p class="c10">
            <span><a href="https://github.com/sora-xor/sora2-network/issues/413">Root (democracy) OR Technical committee</a></span
          </p>
        </td>
      </tr>
      <tr class="c15">
        <td class="c4" colspan="1" rowspan="1">
          <p class="c10"><span class="c9">Custom</span></p>
        </td>
        <td class="c3" colspan="1" rowspan="1">
          <p class="c10">
            <span class="c8"
              >-</span
            >
          </p>
        </td>
        <td class="c6" colspan="1" rowspan="1">
          <ul class="c18 lst-kix_gnd1hip7nte-0">
            <li class="c5 li-bullet-0"><span class="c8">Asset owner</span></li>
            <li class="c5 li-bullet-0"><span class="c8"><a href="https://github.com/sora-xor/sora2-network/issues/413">Root (democracy) OR Technical committee</a></span></li>
          </ul>
        </td>
        <td class="c6" colspan="1" rowspan="1">
          <p class="c10"><span class="c8"><a href="https://github.com/sora-xor/sora2-network/issues/413">Root (democracy) OR Technical committee</a></span></p>
        </td>
      </tr>
      <tr class="c15">
        <td class="c11" colspan="1" rowspan="2">
          <p class="c10"><span class="c9">NFT</span></p>
        </td>
        <td class="c4" colspan="1" rowspan="1">
          <p class="c10"><span class="c9">Non-divisible</span></p>
        </td>
        <td class="c3" colspan="1" rowspan="1">
          <p class="c10">
            <span
              >From any address that has a non-zero balance of the corresponding
              asset</span
            >
          </p>
        </td>
        <td class="c6" colspan="1" rowspan="1">
          <ul class="c18 lst-kix_gnd1hip7nte-0">
            <li class="c5 li-bullet-0"><span class="c8">Asset owner</span></li>
            <li class="c5 li-bullet-0"><span class="c8"><a href="https://github.com/sora-xor/sora2-network/issues/413">Root (democracy) OR Technical committee</a></span></li>
          </ul>
        </td>
        <td class="c6" colspan="1" rowspan="1">
          <p class="c10"><span class="c8"><a href="https://github.com/sora-xor/sora2-network/issues/413">Root (democracy) OR Technical committee</a></span></p>
        </td>
      </tr>
      <tr class="c15">
        <td class="c4" colspan="1" rowspan="1">
          <p class="c10"><span class="c9">Divisible</span></p>
        </td>
        <td class="c3" colspan="1" rowspan="1">
          <p class="c10">
            <span
              >-</span
            >
          </p>
        </td>
        <td class="c6" colspan="1" rowspan="1">
          <ul class="c18 lst-kix_gnd1hip7nte-0">
            <li class="c5 li-bullet-0"><span class="c8">Asset owner</span></li>
            <li class="c5 li-bullet-0"><span class="c8"><a href="https://github.com/sora-xor/sora2-network/issues/413">Root (democracy) OR Technical committee</a></span></li>
          </ul>
        </td>
        <td class="c6" colspan="1" rowspan="1">
          <p class="c10"><span class="c8"><a href="https://github.com/sora-xor/sora2-network/issues/413">Root (democracy) OR Technical committee</a></span></p>
        </td>
      </tr>
    </table>

# DOD
- [ ] https://github.com/sora-xor/sora2-network/issues/412
- [ ] Mechanism implemented

**Comment by bragov4ik** [comment]
Clarification (thanks @wer1st for explanation in DMs):
"Asset owner" means owner of base order book asset.

For example, if an order book is for trading stocks of a company (for USD), the base asset will be stocks, and quote asset is $.
Owner of the stock (the company) in this case is responsible for modifying the order book, but owner of USD has nothing to do with it. The USD is only used as a currency for trading base asset
