### ISSUE TITLE
[Tech debt]: Use TradingPairSourceManager instead of pallet

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#441]
### Problem statement

We call functions directly from pallets. It is necessary to use traits in Config for these calls.
One of such using is managing enabled sources for trading pair in `trading-pair` pallet.

### Description

Replace all calls related to enabled sources for trading pair with using `TradingPairSourceManager `trait.

Note:
Search `// TODO: #441 use TradingPairSourceManager instead of trading-pair pallet` comment in the code. It helps to find necessary places.

### Definition of Done

1. All components get enabled sources info from `TradingPairSourceManager `
2. All tests passed

**Comment by Immanuel-john** [comment]
Hi @wer1st i would like to contribute to this. possible?

**Comment by wer1st** [comment]
> Hi @wer1st i would like to contribute to this. possible?

Hi @Immanuel-john, you can take this and open PR when it's ready
