### ISSUE TITLE
[Tech]: Update branch audit from master

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#445]
### Problem statement

Our bug bounty program is based on the _audit_ branch. We should update it with the latest changes from the _master_ branch, without the features that are still in development.

_audit branch_: https://github.com/sora-xor/sora2-network/tree/audit

### Definition of Done

- [x] audit branch updated

### Requirements

Do not include changes from features that are not tested and/or still in development.

**Comment by vovac12** [comment]
Done
