### ISSUE TITLE
Discrete ALT

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora2-network#447]
Necessary to update `liquidity_proxy::smart_split()` to use several liquidity sources and develop new approach how to estimate the volume of liquidity for each available liquidity source to perform swap.
In fact, it is an implementation of ALT (aggregation liquidity technology) discrete version.

### Definition of Done
- [x] Analysis
- [x] Math model
- [x] Update LiquiditySource trait: add step_quote()
- [x] Introduce chunks of liquidity
- [x] Liquidity Aggregator
- [x] Liquidity Aggregator: fee calculation
- [x] Liquidity Aggregator: tests
- [x] New Smart Split function
- [x] New Smart Split function: rewards calculation
- [x] ~New Smart Split function: tests~
- [x] XYK Pool step_quote
- [x] XYK Pool step_quote: tests
- [x] XYK Pool step_quote: fee
- [x] XYK Pool step_quote: benchmark
- [x] Order Book step_quote
- [x] Order Book step_quote: tests
- [x] Order Book step_quote: fee
- [x] Order Book step_quote: benchmark
- [x] XST Pool step_quote
- [x] XST Pool step_quote: tests
- [x] XST Pool step_quote: fee
- [x] XST Pool step_quote: benchmark
- [x] TBC step_quote
- [x] TBC step_quote: tests
- [x] TBC step_quote: fee
- [x] TBC step_quote: benchmark
- [x] Update liquidity proxy dynamic weight calculation
- [x] Update liquidity proxy max weight calculation
- [x] ~Liquidity proxy Swap tests~

**Comment by wer1st** [comment]
We decided to use the following approach:
1. Divide the incoming amount of liquidity into N equal parts.
2. Estimate the output amount for each part for each available liquidity source. It may also require more optimal methods than quote.
3. Make several rounds in which we select the best parts from different liquidity sources, based on the best output amount, until we reach the required target amount (incoming or outcoming).
4. Sum up the parts of each liquidity source and exchange them.

**Comment by Tieumsan** [comment]
@wer1st please link the (draft) PR to the task

**Comment by wer1st** [comment]
We decided to make the tests in a separate task, because it requires some rework of test system for liquifity proxy
