### ISSUE TITLE
[Tech]: Bridge proxy improvements

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#451]
### Problem statement

We want to use bridge proxy for HASHI and substrate bridge

### Definition of Done

- [x] HASHI bridge compatability
- [x] Substrate bridge compatability

**Comment by ghostit93** [comment]
[Dev] Transfer ROC from Sora mainnet to Another parachain (parachainBridgeApp.InvalidDestinationParachain)
https://app.qase.io/case/PSS-136

[Dev] Transfer ROC from Sora mainnet to Rococo (bridgeProxy.NotEnoughLockedLiquidity)
https://app.qase.io/case/PSS-121

[DEV] bridgeProxy.updateTransferLimit
https://app.qase.io/case/PSS-123

[DEV] bridgeProxy.limitedAssets
https://app.qase.io/case/PSS-122

[DEV] bridgeProxy.addLimitedAsset
https://app.qase.io/case/PSS-119

[DEV] bridgeproxy.updateTransferLimit
https://app.qase.io/case/PSS-118

[DEV]bridgeProxy.consumedTransferLimit
https://app.qase.io/case/PSS-120
