### ISSUE TITLE
[Ecosystem]: Send out rewards from Kusama crowdloan

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#456]
### Problem statement

After we won a new slot for Kusama, we need to send the rewards to the community members that participated in supporting SORA to win the slot.
**Reward per KSM contributed**: 8 TBCD per 1 KSM (https://parachains.info/auctions/kusama-71-75) (confirm with the SORA Council)
**List of contributors**: https://kusama.subscan.io/crowdloan/2011-96 (the list can be verified with a SORAMITSU contributor if needed)

### Definition of Done

- [ ] Reward scheme confirmed w/ Council
- [ ] List of contributed verified
- [ ] Crowdloan rewards sent out to Kusama campaign contributors

**Comment by Tieumsan** [comment]
@vovac12 task for distributing the crowdloan rewards

**Comment by Tieumsan** [comment]
@WRRicht3r Vladimir (@vovac12 ) is working on this. I will ask him to get in touch with you

**Comment by vovac12** [comment]
[prepare-crowdloan-proposal.zip](https://github.com/sora-xor/sora2-network/files/11578729/prepare-crowdloan-proposal.zip)
Script used to generate proposal

**Comment by WRRicht3r** [comment]
Thank you for the update on this. We still need the technical address for these funds. Please notify me once we have it so we can fw to governance.
