### ISSUE TITLE
[Bug]: Incorrect network fee calculation for ADAR extrinsics

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora2-network#464]
### Steps to reproduce

Execute `swapTransferBatch` with several sub-calls

### Actual behavior

Executing `swapTransferBatch`, no matter how many sub-calls are included, the transaction fee will always be 0.07 XOR

### Expected behavior

0.07 XOR is charged for each sub-call

### Environment

{"label"=>"Production"}

**Comment by Tieumsan** [comment]
@bgodlin please move it further to _Product Backlog_ once the tech requirements are ready, we'll manage the prioritisation further in the PB.
