### ISSUE TITLE
[Spike]: Investigate Ink!

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#524]
### Problem statement

Ink! is a new framework to write smart contracts on top of Substrate-based blockchains. 
It is a way to simplify onboarding of new teams building on top of SORA.
We need to assess the production-readiness of Ink! and how new apps built with Ink! would be integrated on the blockchain.

### Definition of Done
**Expected outcome**: PowerPoint or PDF

- [x] Assess production-readiness of the Ink! framework to build smart contracts on SORA
    - Report on the roadmap and milestones, and 
    - Completion status of the implementation of the framework
    - Mention of projects implemented in with Ink! smart contracts
- [x] Short guide on how to integrate Ink! smart contracts on top of SORA
    - Architecture scheme of the communication between the Ink! smart contract and the blockchain
    - Expected differences in performance and data management between using Ink! and building directly in Rust
    - Preferred use cases for using Ink! instead of Rust

**Expected date**: 1st half of August

### Methodology

Research articles, documentation, use cases

### Useful resources

e.g.: https://twitter.com/ink_lang/status/1665708577645027328

**Comment by bgodlin** [comment]
The updated will be published to https://gist.github.com/bgodlin/91edf739a0b67d7a07af11d186223901
