### ISSUE TITLE
[Bug]: Insufficient liquidity on custom synth swap

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#533]
### Preconditions

Think it can happens when Band relay price late. 
Band sends every 4.8-4.9 min. But sometimes it sends 7 min after.
![image](https://github.com/sora-xor/sora2-network/assets/17094492/5afabcc0-7ee6-4044-b9cf-6f0fbfe53cf3)
![image](https://github.com/sora-xor/sora2-network/assets/17094492/17a3ade2-d47f-46e2-9daf-21e0b5bbbfa5)

We need to increase 5 min to 6 min interval (for example)

Band team will investigate this issue too. They suspect that the there's a delay somewhere in the flow that ended up in the final relay being 2-3 minutes late.

### Steps to reproduce

1. Open liquidityProxy.quote rpc and try to execute with XOR-XSTRUB (for example)

### Actual behavior

'None' message

### Expected behavior

User sees the quote anyway 

### Environment

{"label"=>"Stage"}

**Comment by Tieumsan** [comment]
On hold with Under investigation by Band team

**Comment by Tieumsan** [comment]
**Fallback**: Keep the same price if no update.
Stop XST liquidity source automatically if no update after too long (1h)
Update by governance again to restart

cc. @pakrentos @bgodlin @vovac12

**Comment by ra9mls** [comment]
@Tieumsan can we close this task?

**Comment by Tieumsan** [comment]
@ra9mls If the data feeds we receive from the Band chain is fixed, then yes. We will implement the fallback solution in #623
