### ISSUE TITLE
Operations with the balance of indivisible assets

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#542]
The balance =1 of divisible asset is 1 000 000 000 000 000 000
The balance =1 of indivisible asset is 1

It is necessary to adapt all math operations and checks considering this

**Comment by wer1st** [comment]
The solution is to introduce new entity `BalanceUnit` that wraps `Balance` and contains the information about divisibility/indivisibility of the balance. It provides base math operations (+, -, *, /) with balance.

**Comment by ra9mls** [comment]
https://app.qase.io/case/PSS-150
