### ISSUE TITLE
Market orders for non-divisible assets

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#547]
### As a

user

### I want to

trade my non-divisible asset liquidity (NFT)

### So that

I need a mechanism to proceed a swap

### Preconditions

New swap mechanism must be available only for non-divisible assets, for divisible assets should the `liquidity_proxy::swap()` should be used.

### Flow

1. The order book for the asset exists and filled by limit orders.
2. User proceeds a swap by creating a buy/sell market order in OrderBook pallet by associated extrinsic.
3. Exchange executes in the order book

### Postconditions

Depends on buy/sell market order, the user's balance should be changed

**Comment by ra9mls** [comment]
https://app.qase.io/case/PSS-152
https://app.qase.io/case/PSS-151
