### ISSUE TITLE
[Tech]: Dynamic fee calculation

### ISSUE THREAD

**Issue by pakrentos** [sora-xor/sora2-network#553]
### Problem statement

Current implementation of oracle proxy and XST platform allows synthetic assets frontrunning

### Description

Since the current oracle updates prices every five minutes, users could potentially anticipate incoming price changes and profit from trading synthetics. Therefore, we need to implement a dynamic fee calculated based on the percentage change in the oracle price.

The formula for calculation of the dynamic fee should look like this:
$\phi_{D} ( i ) = \tau * \phi_{D} ( i-1 ) + max ( [P_{i} / P_{i-1} - 1  - 2 \delta- \mu], 0 )$
$\phi_D(0) = 0$

The terms are:
|	   Term|							Description|
|:---------|:---------------------------------------|
|        $\delta$ |         Price feed deviation threshold |
|     $P_i$ |         Current epoch (i) oracle price |
|      $\tau$ |             Dynamic fee decay constant |
|        $\mu$ |                    Minimum dynamic fee |
|  $\phi_t(i)$ |   The current epoch’s  (i) dynamic fee |

where epoch denotes the period of time between oracle updates.
Based on: https://sips.synthetix.io/sips/sip-184/?ref=blog.synthetix.io

### Definition of Done

- [x] Implement dynamic fee calculation in Band pallet
- [x] Implement a feature in the XST platform to accommodate the dynamic fee

**Comment by pakrentos** [comment]
## How to set dynamic parameters
- Sudo call band::set_dynamic_fee
- The limits for parameters:
  - 0 ≤ decay < 1
  - min_fee ≥ 0
  - deviation ≥ 0

## How the fee is adjusted in XST platform
- The dynamic fee ratio adds up to the synthetic asset fee ratio
- The sum is the resulting fee ratio

**Comment by ra9mls** [comment]
The additional dynamic fee parameters can be checked with
**band.symbolRates**
