### ISSUE TITLE
[Tech]: Batch nonce for substrate bridge

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#569]
### Problem statement

We should track commitments instead of particular messages in substrate bridge channels as in EVM bridge to reduce payload and enable some additional optimizations in relayer

### Definition of Done

- [ ] Batch nonce in channels instead of message nonce
- [ ] Get commitments by batch nonce in relayer

**Comment by Tieumsan** [comment]
@vovac12 the PRs are merged but the task is still open. What is the latest status of the task ?
Please update accordingly
