### ISSUE TITLE
OrderBook: cancel all my limit orders

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#603]
Create new extrinsic that allows user to cancel all their limit orders in all order books by one request.

**Comment by wer1st** [comment]
What if user have some limit orders in different order books and some of these order books are in statuses that frobid to cancel limit orders.

@Tieumsan @stefashkaa @bgodlin What should we do?
- Return error. In this case user should cancel limit orders (which can be canceled) manully.
- Cancell only limit orders which can be canceled.

**Comment by Tieumsan** [comment]
Please proceed w/ option 3 for now:
Cancel batch. The extrinsic receives a list of orders to cancel and cancel all of them or return an error.
@wer1st 
cc. @stefashkaa
