### ISSUE TITLE
[Tech]: Establish monitoring of ODF relayers account (XST Platform)

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#616]
### Problem statement

Relayers ensure we get the oracle data feed (ODF) for the synthetic assets of the XST platform. 
We need to monitor the account of relayers to ensure 100% uptime in the update of the data feeds for the synthetic assets.

#### Production relayers accounts

- 

### Definition of Done

- [x] Determine clear process for funding relayers' account with external chain partners
- [ ] Establish dashboard and alerts to monitor the balance of relayers

**Comment by Tieumsan** [comment]
@ra9mls @f33r0 please add link to Grafana board for the monitoring of XST platform

**Comment by ra9mls** [comment]
Will added prod accounts for monitoring when they have a tokens.
