### ISSUE TITLE
[Bug]: liquidityProxy.quote amount = 0 when price changes more than 10000 times

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#620]
### Preconditions

BTC price is 35 000

### Steps to reproduce

1. Change BTC price with force.relay to 3,600,000,000,000,000,000,000,000,000
2. call  liquidityProxy.quote for pair xst-btc (example) 

### Actual behavior

Fee becomes more than amount
```
45: liquidityProxy.quote: Option<LPSwapOutcomeInfo>
{
  amount: 0
  fee: 96.3267 kXOR
  rewards: []
  route: [
    0x0200090000000000000000000000000000000000000000000000000000000000
    0x03000f34f3070881c8095a4122780400d7af0000000000000000000000000000
  ]
}
```

### Expected behavior

Fee can't be more 1

### Environment

{"label"=>"Development"}

**Comment by pakrentos** [comment]
Fix will be in this pr: #587
