### ISSUE TITLE
[Tech]: Bridge withdraw limit

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#647]
### Problem statement

We need to implement withdraw limit for Substrate/EVM bridge to improve our protection against hacks

### Definition of Done

- [ ] Add a time limit on outgoing transfers in the BridgeProxy pallet
- [ ] The time limit is the same for each limited asset
- [ ] Apply this new logic to Hashi bridge

### Requirements

- Time period is 1 hour
- Withdraw limit is 50k$ per time period
- Withdraw limit should be changable via root or tech committee

**Comment by ghostit93** [comment]
[DEV]bridgeProxy.consumedTransferLimit
https://app.qase.io/case/PSS-120

[DEV] bridgeproxy.updateTransferLimit
https://app.qase.io/case/PSS-118

**Comment by ghostit93** [comment]
[DEV] bridgeProxy.addLimitedAsset
https://app.qase.io/case/PSS-119
