### ISSUE TITLE
When remove liquidity Output_b_min = 0

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#65]
When remove liquidity Output_b_min = 0.
This should be restricted on chain level and return the error.
The example of the transaction

___
Comment from @KalitaAlexey : It seems the source transaction is invalid. Analyze if output_b_min = 0 causes any issues (pallets/pool-xyk/src/lib.rs:321)

**Comment by wer1st** [comment]
Decided to limit basic and target asset balances and min balances for deposit and withdraw operations
