### ISSUE TITLE
Remove amount_without_impact from quote

### ISSUE THREAD

**Issue by KalitaAlexey** [sora-xor/sora2-network#66]
liquidity_proxy.quote returns amount_without_impact that is most of times inaccurate, should not be used, but takes calculation time.

**Comment by ra9mls** [comment]
Deleted. The result:
```
1: liquidityProxy.quote: Option<LPSwapOutcomeInfo>
{
  amount: 32.9787 mXOR
  fee: 3.0000 mXOR
  rewards: []
}
```
