### ISSUE TITLE
[Tech]: Rework xor-fee

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#662]
### Problem statement

We should rework xor-fee to be able to support more advanced withdraw fee mechanisms such as post dispatch payment depending on result and XOR-less transactions

### Definition of Done

- [x] Move transaction payment signed extension to xor-fee pallet
- [x] Extend ApplyCustomFee trait to support post-dispatch fee payment
- [x] Add DispatchResult to withdraw fee handler

**Comment by javitoarroba** [comment]
XORless fees can also be applied to PSWAP Rewards Claim. 

1 The user claims rewards
2 If there is not required  XOR balance for the fee, the system checks if there are enough rewards for the fee
3 If there are enough rewards, apply post-dispatch fee payment 
4 The system claims rewards and swaps the required XOR fee from PSWAP Rewards.
5 And advise of the net rewards to receive after fee payment is also displayed before tx approval
