### ISSUE TITLE
[Bug]: Wrong calculation on price server for some synth assets

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#684]
### Steps to reproduce

Open https://mof.sora.org/qty/xstbtc
Execute RPC call: assets.totalSupply: balance

### Actual behavior

Price server backs https://mof.sora.org/qty/xstbtc - 0.1520212820045004

RPC call: assets.totalSupply: balance: 1.5202 mXOR

### Expected behavior

Price server backs https://mof.sora.org/qty/xstbtc - 0.001520212820045004

### Environment

{"label"=>"Production"}

**Comment by Tieumsan** [comment]
@ra9mls should this issue be moved to [pricing-server](https://github.com/sora-xor/pricing-server) ?
