### ISSUE TITLE
[Tech]: Swapless transfers in batch swap extrinsic

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#689]
### Problem statement

We need to be able to use existing token balance on account during batch swap

### Definition of Done

1. Add ability to specify amount of tokens which should be used from sender account in `SwapBatchInfo`
2. Add tokens whitelist which can be send in batch swap without any swap

**Comment by adaagava** [comment]
There is a bug with whitelist: https://github.com/sora-xor/sora2-network/issues/739

**Comment by adaagava** [comment]
https://github.com/sora-xor/sora2-network/issues/788
