### ISSUE TITLE
[Tech]: Kensetsu pallet

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#692]
### Problem statement

As part of the development of Kensetsu we need to establish the bases for the data structures of the platform.

### Definition of Done

- [x] Implement **VaultType** interface and data structure
- [x] Creating a new _vaultType_ is possible only through root extrinsic (voted on by Governance)
- [x] Implement Kensetsu **Vault** data structure
- [x] Creating a new _vault_ is possible by executing an extrinsic signed by any user
- [ ] Develop an interface that can connect to both accessible data sources, including price tools and oracles
  - [ ] Initially, ensure that it is connected only to price tools

### Data Structures

In the blockchain storage, there are three main entities: **`VaultType`**, **`Vault`**, and **`Account`**.

Starting with the `VaultType`, any operation on this entity will require the root call origin. Its purpose is to serve as a whitelist for permissible vaults that can be created. As shown in the diagram, it possesses an integral primary key. This primary key is `collateral_asset`. Properties are `debtLimit`, `collateralisation_ratio`, `liquidation_ratio`, `stability_fee`, which altogether define the unique `VaultTypeId`.

The `Address` entity simply represents a user address, and it has been present in the network since the genesis block.

To create a specific vault linked to a user, it is necessary to first have the corresponding vault type established and approved by governance. Only then will a user be able to deposit collateral and receive `KUSD` in return.

#### VaultType
VaultType is an interface that all vaults created must implement.
- `collateral_asset`: CommonPrimitivesAssetId32
- `debt_limit`: u128
- `collateralisation_ratio`: u128
- `stability_fee`: u128

#### Vault
Vault is the data structure that enables users to borrow KUSD against a collateral asset.
- `vault_type`: VaultTypeId
- `address`: AccountId32
- `amount_collateral`: u128

The extrinsics available to interact and modify the state of a particular vault will be detailed in other tasks and features.

**Comment by ra9mls** [comment]
https://app.qase.io/case/PSS-161
