### ISSUE TITLE
[Tech]: KUSD tokenomics

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#695]
### Problem statement

As part of the implementation of the Kensetsu platform we need to create and implement the tokenomics of the platform's stablecoin: KUSD

### Definition of Done

- [ ] KUSD token created

#### KUSD
`asset_name`: SORA Kensetsu USD
`asset_symbol`: KUSD
`initial_supply`: TBD
`is_mintable`: True
`is_indivisible`: False
`opt_content_src`: TBD (To Be Determined)
`opt_desc`: TBD

#### Tokenomics
To encourage XOR-KUSD liquidity, a percent of the stability fees collected would go to LPs that stake their XOR-KUSD liquidity on Demeter farm.

**Comment by Victorius** [comment]
Distribution of tokens from stability fee for Type 2 Vault: 
- Portion 1 goes to Demeter Farm to incentivise users to stake XOR-KUSD.
- Portion 2 goes to technical account (for some operations).

In case Bad Dept should we burn need amount of KUSD to minimise Bad Dept metric in protocol.

Bad Dept metric measures in KUSD
- amount of minted unbacked KUSD in protocol (we can calculate it after finishing liquidation process for Type 2 Vaults).

**Comment by Victorius** [comment]
Portion 2 is main destination for stability fee for Phase 1.
