### ISSUE TITLE
[Feature]: Withdraw collateral from a vault

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#697]
### As a

borrower of KUSD

### I want to

remove collateral from my vault

### So that

I can use my assets previously locked for another purpose

### Preconditions

The user has created a vault of vaultTypeID

### Flow

1. The user selects the _amount_ of _collateral_asset_ they want to withdraw from the vault
2. The system verifies that the _amount_ of KUSD borrowed by the user is less than the remaining collateral after the withdraw (in dollar value)
3. The system sends the _amount_ of _collateral_asset_ to the user
4. The system updates the storage
5. The system emits an event

See `kensetsu. withdraw_collateral`

### Postconditions

The user has received the _amount_ of _collateral_asset_ they wanted to withdraw
The amount of collateral in the vault of vaultTypeID-userAddress pair has been reduced by _amount_.

**Comment by ra9mls** [comment]
https://app.qase.io/case/PSS-162
