### ISSUE TITLE
[Feature]: Set debt limit for a vaultType

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#699]
### As a

governance actor

### I want to

modify the debt limit for a specific type of vault

### So that

I can adapt the conditions of borrowing against a certain type of vault

### Preconditions

The vaultTypeID is valid

### Flow

1. The user determines the value of the debt_limit for the chosen vaultTypeID
2. The system creates a preimage with the parameter `vaultTypeID`, `debt_limit` to enable the execution of the `kensetsu.setDebtLimit`. The extrinsic can only be executed after Governance vote.

### Postconditions

The debt_limit parameter for the vaults of vaultTypeID has been updated with the new value of debt_limit.

**Comment by ra9mls** [comment]
Will be in https://github.com/sora-xor/sora2-network/issues/1099
