### ISSUE TITLE
[Feature]: Set collateral stability fee for a vaultType

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#700]
### As a

governance actor (council) or Kensetsu Risk Assessment Committee

### I want to

modify the collateral stability fee for a specific type of vault

### So that

I can adapt the conditions of borrowing KUSD against a certain type of vault

### Preconditions

The vaultTypeID is valid

### Flow

1. The user determines the value of the _stability_fee_ for the chosen _vaultTypeID_
2. The system creates a preimage with the parameter vaultTypeID, _stability_fee_ to enable the execution of the `kensetsu.setCollateralStabilityFee`. The extrinsic can only be executed after Governance vote.

### Postconditions

The _stability_fee_ parameter for the vaults of vaultTypeID has been updated with the new value of stability_fee.

**Comment by ra9mls** [comment]
Will be developed in https://github.com/sora-xor/sora2-network/issues/1099
