### ISSUE TITLE
Sora2 - Update dependencies For Parity Bridges Common

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#71]

**Comment by N1ghtStorm** [comment]
There is an issue:
https://github.com/paritytech/polkadot/issues/5753

**Comment by Tieumsan** [comment]
Question from @bragov4ik : https://substrate.stackexchange.com/questions/3845/how-parity-bridges-common-is-intended-to-be-used-for-development

**Comment by bragov4ik** [comment]
Successfully updated the dependencies (only locally)
Failed to move the build to remote dependencies, compile errors remained.

Decided not to waste time on it for now

**Comment by bragov4ik** [comment]
https://soramitsu.atlassian.net/l/cp/oa9E6iJm
