### ISSUE TITLE
[Feature]: Reconsider security of update_orderbook

### ISSUE THREAD

**Issue by bragov4ik** [sora-xor/sora2-network#723]
### As a

stakeholder

### I want to

have `update_orderbook` extrinsic executed by a blockchain

### So that

number of orders executed after this is kept within expected limits

### Preconditions

Someone updates parameters of an order book

#### Parameter ratio

We want `min_lot_size` and `max_lot_size` parameters to restrict extrinsics `place_limit_order`, `execute_market_order`, and `exchange` from executing too much orders at once. In particular, maximum number of executed orders is $\frac{\text{max lot size}}{\text{min lot size}}$ (assuming all existing orders satisfy the boundaries). This number should not be greater than some cap $N$: $\frac{\text{max lot size}}{\text{min lot size}} \leq N$

This $N$ should equal to some number of orders, executing which easily fits into the block (< 2 sec, better < 1 sec to be safe). According to benchmarking performed in #565, an appropriate value would be $N = 1000$.

#### Parameters update

However, this becomes more complicated when we consider changing the parameters. `update_orderbook` does not enforce new `min_lot_size` on existing orders. It means that it is possible to bypass the aforementioned restriction ($N$) by placing many orders before increasing both limits on order size. For example,
- *parameters: min_lot_size=10 max_lot_size=10000* | create 100000 orders with `amount=10` (minimal possible)
- *parameters: min_lot_size=1000 max_lot_size=1000000* | update the parameters (increase both 100 times)
- *parameters: min_lot_size=1000 max_lot_size=1000000* | execute market order with amount 1000000 (max amount): all 100000 orders are used and affected

As we can see, some additional measures to prevent such behaviour are needed. We suggest manual approach for solving this: restricting `update_orderbook` to be callable only by technical collective or root (through democracy). This way it is possible to review the contents of the order book before updating the parameters to spot such malicious behaviour and stop an attack.

#### Additional safety net

For the manual mechanism to work it is also needed to block creation of orders during the voting process (to prevent filling up order book right before voting closes), as well as close attention by the voters. This does not seem like a robust criteria and these checks are easy to forget. Therefore, we suggest to restrict raising `max_lot_size` in order to prevent such inattentiveness.

Additionally to $\frac{\text{max lot size}}{\text{min lot size}}$, `update_orderbook` should also check $\frac{\text{max lot size}\_{\text{new}}}{\text{min lot size}\_{\text{old}}}$ so that:
- If voters did not check the order book, maximum number of executed orders is still satisfactory
- If trading is not stopped, placing many $\text{min lot size}\_{\text{old}}$ orders when the voting is almost over doesn't allow to execute too many orders after the fact

This ratio can be checked with a larger $N_\Delta$. For example, $N_\Delta = 4000$. In order to raise the upper bound more than this ratio allows, it is possible to call (place on vote) `update_ordebook` multiple times, which should draw more attention to the order book.

### Postconditions

The parameters are accepted or declined based on the validity check.

### Definition of Done

- [ ] $\frac{\text{max lot size}}{\text{min lot size}}$ is verified on update
- [ ]  Asset owners are not allowed to update parameters directly
- [ ] $\frac{\text{max lot size}\_{\text{new}}}{\text{min lot size}\_{\text{old}}}$ is verified on update

**Comment by bragov4ik** [comment]
Preliminarly, $N=1000$

**Comment by wer1st** [comment]
@bragov4ik looks like #748 should cover all cases. Please check it and close this ticket. Or add additional security points here

**Comment by bragov4ik** [comment]
Closed in favor of https://github.com/sora-xor/sora2-network/issues/748
