### ISSUE TITLE
[Tech]: Rename SubstrateApp to ParachainApp

### ISSUE THREAD

**Issue by N1ghtStorm** [sora-xor/sora2-network#730]
### Problem statement

ParachainApp is more relevant name

### Definition of Done

Rename Palley

**Comment by N1ghtStorm** [comment]
PR sora2-common

https://github.com/sora-xor/sora2-common/pull/59

PR sora2-parachain

https://github.com/sora-xor/sora2-parachain/pull/143

**Comment by ghostit93** [comment]
[DEV] parachainBridgeAp - assetKinds
https://app.qase.io/case/PSS-80

[DEV] parachainBridgeApp.setMinimumXcmIncomingAssetCount

[DEV] parachainBridgeApp.removeAssetidParaId
https://app.qase.io/case/PSS-137
https://app.qase.io/case/PSS-128

[DEV] parachainBridgeApp.addAssetIdParaId
https://app.qase.io/case/PSS-116
