### ISSUE TITLE
[Tech]: Remove old limiter from ParachainApp(old name SubstrateApp)

### ISSUE THREAD

**Issue by N1ghtStorm** [sora-xor/sora2-network#733]
### Problem statement

There is a limiter that is not used due to advanced limiter that is based on reference token price in liquidity pools

### Definition of Done

1. Remove limiter and its tests and benchmarks

**Comment by N1ghtStorm** [comment]
PR https://github.com/sora-xor/sora2-common/pull/60

**Comment by Tieumsan** [comment]
@N1ghtStorm @ra9mls should we close this issue ?
