### ISSUE TITLE
[Tech]: Prepare Generic Substrate App

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#735]
### Problem statement

We want to be able to make bridges with standalone Substrate networks and to achieve this we need to have such app

### Definition of Done

- [ ] Add SubstrateApp messages to bridge message ABI
- [ ] Add support for generic asset id type (currently only H256 is supported)
- [ ] Add extrinsics to manage asset registration between standalone networks (there's should not be "master" network)

**Comment by N1ghtStorm** [comment]
PR 

https://github.com/sora-xor/sora2-common/pull/69
