### ISSUE TITLE
[Bug]: BridgeProxy Does not update successful transactions to Done

### ISSUE THREAD

**Issue by N1ghtStorm** [sora-xor/sora2-network#747]
### Steps to reproduce

Send tokens from Sora to a Relay chain.

### Actual behavior

After XCM is sended - the parachain sends message about success and brigdeProxy does not change status to done, it is still in "Commited"

### Expected behavior

After XCM is sended - the parachain sends message about success and brigdeProxy should change transaction status to Done.

### Environment

{"label"=>"Development"}

**Comment by N1ghtStorm** [comment]
Reproduces only in develop

**Comment by Tieumsan** [comment]
@N1ghtStorm @ra9mls what is the status of this task ?
cc. @vovac12

**Comment by pg-vlad** [comment]
Checked on dev
