### ISSUE TITLE
[Tech]: Updating order book attributes optimization

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#748]
### Problem statement

By benchmarks (https://github.com/sora-xor/sora2-network/issues/565) we found that there are special cases when updates of min & max order amount could lead to an increase in the number of limit orders that can be executed by one market order. Potentially, the number of these orders may be too large for one block.

### Description

`max / min` division result gives us approximately the max number of limit orders with `min` amount that could be executed by one market order with `max` amount at one time. We need to control the proportion of `min` & `max` order amount values.

During the updating the attributes we have old and new values of the attributes. Let's use terms: `old_min`, `old_max`, `new_min`, `new_max` below.

It is necessary to inroduce 2 new configs: `SoftMinMaxRatio = 1000` & `HardMinMaxRatio = 4000` into the order book pallet.

Check the following conditions to be sure that we always have the correct values that considers existing orders:
- `(new_max / new_min) <= SoftMinMaxRatio` - limit max number of new orders that can be executed with a new (market) order
- `(new_max/ old_min) <= HardMinMaxRatio` - limit max number of old orders that can be executed with a new (market) order and still allow increasing `max`

Even if we introduce the rules above, it is still possible to break them. All you need is just call `update_orderbook` extrinsic twice.
To prevent it we need to be sure that this extrinsic can be called only by trusted and competent people. Therefore, we should deny an asset owner to call it. Only root & tech committee should be eligible, since they are going to spot such abuse of the extrinsic. Note that the restrictions on new parameters still remain as a safety net.

### Definition of Done

- [x] User **can** call `update_orderbook` extrinsic if the status is `OnlyCancel` or `Stop`.
- [x] User **cannot** call `update_orderbook` extrinsic if the status is `Trade` or `PlaceAndCancel`.
- [x] `(new_max / new_min) <= SoftMinMaxRatio`
- [x] `(new_max/ old_min) <= HardMinMaxRatio`
- [x] Asset owner cannot call `update_orderbook` extrinsic anymore
- [x] Unit tests
- [x] Update benchmarks
- [x] Update autotests if it necessary

### User scenario
Update order-book from the user perspective:
1. Announce the updating of order book for the pair.
2. Change order-book status to `Stop`.
3. Call `update_orderbook` extrinsic with new attributes.
4. Wait for the update to complete.
5. Change order-book status back.

### Requirements

Take an approve from @Tieumsan & @bgodlin that we forbid an asset owner to modify the order book attributes.

**Comment by wer1st** [comment]
@bgodlin this task changes the requirements of #400

**Comment by wer1st** [comment]
Probably we can leave an ability for an asset owner to update attributes and don't forbid this. Looks like new limitations should prevent all our security concerns. Need to discuss.

**Comment by bragov4ik** [comment]
It seems possible to split the task into
- alignment scheduling
- max/min ratio

Just adding since AFAIR you mentioned an intention to split it later

**Comment by bragov4ik** [comment]
I'm thinking if instead of SMALL/BIG naming it SOFT/HARD would make more sense 🤔 (as in soft/hard limit)

**Comment by wer1st** [comment]
> @wer1st Does this mean that the Order book will be unusable while the alignment is ongoing ?

Yes. If you look at the user scenario, you can see that democracy/tech committee should to change the status and forbid trades for a while. It will be impossible to update the order book if trades are allowed.
Also, it will be impossible to change the status and allow trades, untill the alignment finished

**Comment by wer1st** [comment]
We get the approve from @Tieumsan that we forbid an asset owner to modify the order book attributes.

**Comment by wer1st** [comment]
Moved the scheduling of alignment in new task #764
