### ISSUE TITLE
QA Tools: initialize liquidity source

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#749]
### As a

dev / qa

### I want to

Initialize some liquidity source for a trading pair

### So that

I can setup a necessary preconditions much faster and don't waste my time to remember all requiremenst for the liquidity source.

### Preconditions

The liquidity source for given trading pair is not initialized.

### Flow

1. Dev / QA selects the `qa-tools` pallet in polkadot.js
2. Select associated extrinsic to initialize the liquidity source by one call
3. Enter trading pair and other specific data (pool reserves, order book spread prices, etc.)
4. Call the extrinsic

### Postconditions

The liquidity source for current trading pair is initialized and available for exchange.

### Tech requirements

The main functions for liquidity source initializing must be separate from the extrinsics. They need to be available for call from the extrinsics and from other pallets. It might look like global test utils that provide shortcuts to initialize liquidity source. This will be used by qa-tools extrinsics and unit tests form other pallets.

**Comment by bragov4ik** [comment]
- [x] Order book
  - [x] Tests
- [x] Xyk pool
  - [x] Tests
- [ ] XST
  - [x] Initialize base assets (synthetic base - XST & reference - DAI)
    - [ ] Tests
  - [ ] Initialize synthetics
    - [ ] Tests
