### ISSUE TITLE
[Bug]: Relayer Uses Beefy Light Client to get NetworkId 

### ISSUE THREAD

**Issue by N1ghtStorm** [sora-xor/sora2-network#751]
### Steps to reproduce

Launch relayer

### Actual behavior

It uses Beefy Light client

### Expected behavior

Must Use constant from channels

### Environment

{"label"=>"Development"}

**Comment by N1ghtStorm** [comment]
To QA team - just ensure that brigde works

**Comment by Tieumsan** [comment]
@N1ghtStorm @ra9mls what is the status of this task ?
cc. @vovac12
