### ISSUE TITLE
[Tech]: scheduling of order-book alignment

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#764]
### Problem statement

There may also be a situation when updating of attributes initiates limit orders alignment. This alignment could be too large for one block.

### Description

A possible alignment of limit orders must fit into one block. It is necessary to schedule this alignment in parts, where the max count of aligned orders is `SoftMinMaxRatio`.
To prevent the changing of limit orders during the update, the status must be `Stop`.

We can have a situation when attributes are updated and extrinsic has finished, but the alignment still goes on. User should not be able to change the order book status to `Trade` or `PlaceAndCancel` during the alignment or call updating. We need to add new internal tech status of order book with only 2 statuses:
- `Ready`
- `Updating`

Or some other names with the same meaning.

When the order book has tech status `Ready`, there are no any limitations.
When the order book has tech status `Updating`, user cannot change the status to `Trade` or `PlaceAndCancel` or call `update_orderbook` extrinsic.

_Note:_ the alignment doesn't take too much time. If we assume that order book is filled up, then with current bounds the alignment takes maximum 3 hours.

### Definition of Done

- [x] User **cannot** call `update_orderbook` extrinsic if the tech status is `Updating`.
- [x] User **can** call `update_orderbook` extrinsic if the tech status is `Ready`.
- [x] User **cannot** change the status to `Trade` or `PlaceAndCancel` if the tech status is `Updating`.
- [x] User **can** change the status to `OnlyCancel` or `Stop` if the tech status is `Updating`.
- [x] User **can** change the status to any value if the tech status is `Ready`.
- [x] The alignment of limit orders is scheduled in parts.
- [x] When alignment is done, the tech status is set as `Ready`.
- [x] Unit tests

**Comment by ra9mls** [comment]
Was checked during the load testing https://app.qase.io/case/PSS-157
