### ISSUE TITLE
Pools - Research possibility for XSTUSD-based pools

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#77]

**Comment by Nolan730** [comment]
I think duplicating xyk pool pallet then putting 1-2 function and editing swap function and quote function at liqudityProxy should be enough

**Comment by Tieumsan** [comment]
Lot of work because of substantial modification required in base token.

Can be done in case of free resources.
Otherwise wait to see if it will be included in SORA v3
