### ISSUE TITLE
[Tech]: QA Tools Pallet improvements 

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora2-network#798]
### Problem statement

Now we can fill the order book with limit orders with parameters:
base, quote AssetId and we have following settings:
QaToolsPalletsOrderBookToolsOrderBookFillSettings
bestBidPrice and bestAskPrice
When we use this pallet we can fill the order book with orders with very short deviation:
![image](https://github.com/sora-xor/sora2-network/assets/17094492/941fde00-e186-4fd2-bdc7-c02f9765ca79)

### Definition of Done

- [x] all prices are exposed as `Balance` in interface (for convenience; since quote assets are XOR and XST - both divisible)

User can choose:
- [x] best/worst prices; separately for bids/asks
- [x] price step; separately for bids/asks
- [x] count of limit orders per price; separately for bids/asks
- [x] (optional field) limits for min/max of random order amount. default - min/max lot size.

### Requirements
Parent task: https://github.com/sora-xor/sora2-network/issues/557

**Comment by bragov4ik** [comment]
Found bugs/requested improvements:
- [ ] fix events (#830)
- [ ] fix infinite loop with 0 price step
- [ ] allow switching off bids/asks side in fill settings
- [ ] more descriptive random range
