### ISSUE TITLE
[Bug]: xorFee.ReferrerRewarded. The portion of fee is not sent to the referrer (new accounts)

### ISSUE THREAD

**Issue by pg-vlad** [sora-xor/sora2-network#827]
### Preconditions

**Сreate 2 new accounts for the referrer and the referral**

### Steps to reproduce

1) Link accounts via invitation link
2) Sign transactions with the referral account

### Actual behavior

Event **xorFee.ReferrerRewarded** is displayed on transaction details, but the wrong referrer account is displayed

<img width="854" alt="xorFee ReferrerRewared" src="https://github.com/sora-xor/sora2-network/assets/55486343/efa7fb1e-5645-40f2-9305-d33d8c2ab1be">

### Expected behavior

The portion of fee is sent to the referrer account

### Environment

{"label"=>"Production"}

**Comment by pg-vlad** [comment]
In this case: referrals:referrers

<img width="1673" alt="referrals_referrers" src="https://github.com/sora-xor/sora2-network/assets/55486343/a82b9935-7efc-475f-a675-e8dac81905f4">

**Comment by Tieumsan** [comment]
@TheLedgerOfJoudi please link the PR to the task and push for review so that we can prepare the runtime upgrade for next week.
cc. @vovac12

**Comment by pg-vlad** [comment]
Checked on stage
