### ISSUE TITLE
OrderBook: remove the price corridor check

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#838]
There is a feedback where users ask to remove the price corridor check (now it is 50% both ways).

### How it works now
Users cannot place a limit order with the price that differs from the best bid/ask by 50%.

For example: we have an order book with best bid price is 10 and the best ask price is 11.
Users cannot place a bid limit order with price 5 or lower or place an ask limit order with price 16.5 or higher.

### Motivation of the restriction
It is a safe mechanism that allows to prevent large price swings and manipulations.

Let's discuss it here and decide should we remove this mrchamism or keep it? Probably we can change the 50% value to another.

@takemiyamakoto @Tieumsan

**Comment by wer1st** [comment]
https://www.funderbeam.com/help/what-is-a-price-corridor/

**Comment by wer1st** [comment]
https://www.deutsche-boerse.com/dbg-en/media/deutsche-boerse-spotlights/spotlight/Protection-in-extreme-situations-150532

**Comment by wer1st** [comment]
I think we can stay with this mechanism, it doesn't impact conscientious users

**Comment by RustemYuzlibaev** [comment]
also vote for keeping this mechanism (and probably adjusting percentage value)
a particular stock book can end up when, on one side, there are all orders by extreme low prices and the other side contains extremely high ones. It would lead to dead trading activity (especially with low liquidity provision on a pair)

**Comment by Tieumsan** [comment]
@wer1st I think we can keep the price corridor check

**Comment by wer1st** [comment]
@takemiyamakoto decided to remove this check.
We take it into the release
