### ISSUE TITLE
[Bug]: Review and fix TBCD burn logic

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#876]
### Preconditions

Initialized TBC pool

### Steps to reproduce

Any swap on TBC pool

### Actual behavior

Burned TBCD is 5% of burned VAL

### Expected behavior

Burned TBCD is 10% of burned VAL

### Environment

{"label"=>"Production"}

**Comment by bragov4ik** [comment]
Checked/traced events produced during actual swaps, the 5% is confirmed.

**Comment by bragov4ik** [comment]
> Checked/traced events produced during actual swaps, the 5% is confirmed.

Actually, the [documentation](https://wiki.sora.org/tbc.html#why-is-the-token-bonding-curve-useful) states the same numbers.
Checking the events produced during swaps confirms the same distribution (here's the output from a script that I wrote):
<img width="357" alt="image" src="https://github.com/sora-xor/sora2-network/assets/8144358/f9705dee-e69f-415d-8b8b-18746898ead6">

So the actual behaviour seems to match the documentation. Need to clarify why 10% is expected here.

**Comment by Tieumsan** [comment]
@bragov4ik from the wiki https://wiki.sora.org/tbcd.html

**Comment by bragov4ik** [comment]
> @bragov4ik from the wiki https://wiki.sora.org/tbcd.html

Thanks, apparently the bug description is a little bit misleading. Swaps work according to specification, buy back and burn work as expected. I'll investigate other parts of the TBC mechanism and figure out the steps to reproduce. (of course it includes collaboration with colleagues, where applicable)

**Comment by bragov4ik** [comment]
By the way, if you already know how to reproduce it and where to look for, I would appreciate sharing it here @Tieumsan 
It will make process of understanding the bug quicker 🙏

**Comment by bragov4ik** [comment]
Apparently, [this logic](https://github.com/sora-xor/sora2-network/blob/37e31ff42dcaf8d3caa71c25e047e06635bbb41f/pallets/xor-fee/src/lib.rs#L614) is responsible for the processes mentioned in the bug.

The parameters seems correct, I'll try to find corresponding events in the live network.

**Comment by bragov4ik** [comment]
This remint mechanism is triggered on end of each epoch. One of the blocks where it happened can be found here:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.mof.sora.org#/explorer/query/14158479
Investigating the system events inside this block yields the following activity:
```
[0]: TRANSFER: <mint> -(XOR)-> tech_account: 82946.18727465
[1]: EXCHANGE: tech_account: 82946.18727465(XOR) ---> tech_account: 71.33891791816914(VAL)
[2]: EXCHANGE: tech_account: 82946.18727465(XOR) ---> tech_account: 71.33891791816914(VAL)
[3]: EXCHANGE: tech_account: 7.133891791816915(VAL) ---> tech_account: 8308.398393514231(TBCD)
[4]: TRANSFER: tech_account -(TBCD)-> <burn>: 8308.398393514231
[5]: TRANSFER: tech_account -(VAL)-> <burn>: 64.20502612635224
```
```
Burned TBCD in percentage of reminted VAL: 10.0
Burned VAL in percentage of reminted VAL: 90.0
```

**Comment by bragov4ik** [comment]
This shows that, to the best of my knowledge, the actual behaviour actually matches the expected behaviour (in particular, BBB during remint).
