### ISSUE TITLE
[Tech]: Add `description` field to `swap_transfer_batch` extrinsic

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#897]
### Problem statement

We need to provide additional data for clients in `swap_transfer_batch`, but batched calls is restricted for swaps

### Definition of Done

- [x] Add optional `description` field for `swap_transfer_batch` extrinsic
- [x] Add `description` field data to `BatchSwapExecuted` event

### Requirements

Maximum field length is 2000 bytes

**Comment by bragov4ik** [comment]
clarified in dm: the data can be an arbitrary byte set (i.e. not necessarily a valid utf-8 string).
