### ISSUE TITLE
QA Metrics

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#91]
List the metrics and business metrics that we want to monitor and support the quality of the network.

**Definition of Done**
- List of currently available metrics
- List of all the metrics that we want
- List of data sources from which we can build those metrics

**Comment by adaagava** [comment]
https://docs.google.com/spreadsheets/d/1cMQw0XoNEbonsXvEhAZdupNtizrHKUKIYvY8Zd1-kGY/edit?usp=sharing
The list of metrics that we want

**Comment by adaagava** [comment]
Waiting for #103
