### ISSUE TITLE
[BLOCKCHAIN] KEN token vulnerabilities

### ISSUE THREAD

**Issue by Victorius** [sora-xor/sora2-network#911]
Problem statement
Ken token Tokenomics was released with update for using token - https://medium.com/@shibarimoto/kensetsu-ken-356077ebee78

### Description
**the First Vulnerability** 
Need to describe a vector of attack on KEN token
Use case:
0. Buy Ken Token
1. deposit collateral token
2. borrow stablecoin (protocol will buy back KEN token by bad price)
3. repay debt 
4. Sell KEN token (with profit)

**the second Vulnerability**
Another vulnerability is unbacked KUSD token that will be minted without collateral tokens as 1% extra.

**The third vulnerability**
Absence of liquidity pools on polka swap (KUSD-XOR, KEN-XOR at least)

Definition of done
- [x] Sequence diagram for vector attack on KEN token
- [x] Description of vulnerability on Confluence

**Comment by Alexey-N-Chernyshov** [comment]
The minting of extra stablecoin to buy back KEN token exposes the following vulnerabilities:

1. The triggering of this process by the client allows for potential manipulation of the KEN/XOR and stablecoin/XOR xyk LP. This process is almost cost-free for the client, who only pays the transaction fee to mint stablecoins.
2. The minted stablecoins are not backed by any collateral, resulting in an increase in their circulation and potential deviation from the target price.

Solutions:

1. Implement a KEN token buybacks for stability fee.
2. Introduce a borrow tax mechanism where clients willing to borrow 100 KUSD would receive only 99 KUSD, with the remaining 1 KUSD used for KUSD buybacks.
