### ISSUE TITLE
[Blockchain] KEN tokenomic research

### ISSUE THREAD

**Issue by Victorius** [sora-xor/sora2-network#912]
Statement

Description
1. Find an answer for initial supply for KEN token
2. KEN token distribution after burning process
3. Initial liquidity with KEN token xyk LP.

Definition of done
- [x] Page with description on confluence

**Comment by Alexey-N-Chernyshov** [comment]
https://soramitsu.atlassian.net/wiki/spaces/SB/pages/4333043721/KEN
