### ISSUE TITLE
Rework the outcome fee

### ISSUE THREAD

**Issue by wer1st** [sora-xor/sora2-network#925]
Now fee is returned from `quote` just as a `Balance` that supposed it is volume of XOR asset.
However, the trading fee can be charged in XOR, XST or XSTUSD assets depends on the liquidity source.
Moreover, if `swap` uses several liquidity sources (ALT), the fee may consist of several assets.

Necessary to change the `SwapOutcome` struct and provide the details about fee in results of `quote` and `swap` methods.

### Solution:
```rust
pub struct OutcomeFee<AssetId: Ord, AmountType>(pub BTreeMap<AssetId, AmountType>);


pub struct SwapOutcome<AmountType, AssetId: Ord> {
    /// Actual swap output/input amount including deduced fee.
    pub amount: AmountType,
    /// Accumulated fee amount.
    pub fee: OutcomeFee<AssetId, AmountType>,
}
```

**Comment by Tieumsan** [comment]
@wer1st we need to announce the change to the community once this task reaches public env. to let everyone enough notice to prepare for the change on production.

cc. @vovac12

**Comment by wer1st** [comment]
> this task reaches public env.

Do you mean Stage env?

**Comment by Tieumsan** [comment]
> > this task reaches public env.
> 
> @Tieumsan Do you mean Stage env?

@wer1st  Yes

**Comment by wer1st** [comment]
RPC response diff in general form

<img width="689" alt="image_2024-03-18_16-48-41" src="https://github.com/sora-xor/sora2-network/assets/7015561/f66862e5-3498-4bee-bd40-36585957b144">
