### ISSUE TITLE
[BLOCKCHAIN] Minimum limit

### ISSUE THREAD

**Issue by Victorius** [sora-xor/sora2-network#955]
**Problem statement**
Current implementation allows to create a zero-deposit collateral CDP. Enormous amount of CDO will lead to increasing for time calculation and affect blockchain. As solution here should be a introducing minimum amount for collateral deposit.

**Description**
Necessary to change extrinsic call that will have restriction with minimum amount of depositing collateral token.
This amount should be changeble. 

**Definition of done**

**comments**
For future releases suggestion is to implement limitation related to USD. Where parameter minimum amount to deposit is provided in USD equvalent.

**Comment by Alexey-N-Chernyshov** [comment]
#952
