### ISSUE TITLE
[Blockchain] Closing vault (withdraw collateral)

### ISSUE THREAD

**Issue by Victorius** [sora-xor/sora2-network#956]
**Problem statement**
Regarding RFP we have not partial withdraw of collateral token. It means that during closing vault procedure we will withdraw all amount of collateral token and we can skip the step with withdraw collateral on layouts.

**Description**
* In close vault extrinsic add withdraw operation for 100% amount of collateral tokens.

**Definition of done**

**Comment by Alexey-N-Chernyshov** [comment]
#954
