### ISSUE TITLE
[BLOCKCHAIN] Slippage for Creation CDP

### ISSUE THREAD

**Issue by Victorius** [sora-xor/sora2-network#964]
**Description**
**Use case** - [Blockchain] As a user I'd like to input as max as possible borrow value during the vault creation or borrow more. 

**Problem statement**
Since these operations can be executed with some delay we cannot guarantee that this TX will be executed successfully.
To avoid failed TXs, we need to prepare some sort of slippage tolerance for several extrinsics cuz we use price tools:
1) kensetsu.createCdp
2) kensetsu.borrow

**Definition of Done**
- [ ] Implementation of slippage in createCdp
- [ ] Implementation of slippage in borrow

**Comment by Alexey-N-Chernyshov** [comment]
We agreed to implement this, but I see very little benefit from this because borrowing up to max allowed amount will trigger liquidation in the next block with very high chance.
