### ISSUE TITLE
[Feature]: Enable/Disable TBC and XST liquidity sources

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-network#98]
### As a

Council member

### I want to

Enable/Disable the TBC and XST liquidity sources

### So that

I can prepare the SORA ecosystem for the Ethereum Merge

### Preconditions

The TBC and XST liquidity sources are enabled/disabled (if was disabled/enabled).

### Flow

1. The council votes on disabling the TBC and XST liquidity sources for X block time (X is optional)
2. The TBC and XST liquidity sources are disabled **by root** for X block time, or indefinitely if X was not indicated

### Postconditions

The TBC and XST liquidity sources are disabled/enabled (if was enabled/disabled).

**Comment by Tieumsan** [comment]
Adding extrinsic to enable or disable

**Comment by wer1st** [comment]
Should we have an ability to lock any liquidity source?
Can we lock only one liquidity source? Should it be (lock XST or lock TBC) or always (lock XST and TBC) ?

**Comment by Tieumsan** [comment]
Disabled/Enabled separately. Only TBC and XST

**Comment by wer1st** [comment]
I need to clarify some behavior.
For example:
**Given:**
TBC liquidity source is disabled

**When:**
User calls swap() from liquidityProxy and inputs TBC and XYKPool as liquidity sources.

**Then:**
Should node just remove TBC from user's list and try to swap or return error?

**Comment by wer1st** [comment]
We need to change common behavior and perform time verification for **X block time** each block.
I suggest to remove X time requirement from the task and use **Scheduler** instead for the same functionality.

**Comment by Tieumsan** [comment]
After discussion with @wer1st :
- We'll use the Scheduler
- Verifying each block would put unnecessary load on the blockchain as this action is performed in exceptional cases
- The Scheduler is already used for some extrinsics

**Comment by wer1st** [comment]
Should we disable/enable liquidity source for whole network or for specific DEX?
