### ISSUE TITLE
[Tech]: Remove assets::Config from another pallets

### ISSUE THREAD

**Issue by vovac12** [sora-xor/sora2-network#983]
### Problem statement

We need to reduce amount of direct dependencies between pallets and use traits instead

### Definition of Done

- [ ] Replace usage of assets pallet public functions by associated trait method calls
- [ ] Remove assets::Config from pallets Config supertraits

**Comment by Tieumsan** [comment]
@vovac12 has this issue already been included in a release ?
Otherwise we should include it.
